<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;
use App\Models\EmploymentDetail;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $employees = [
            [
                'first_name' => 'Francis',
                'middle_name' => 'Torrazo',
                'last_name' => 'De la Cruz',
                'email' => 'aulskelly@gmail.com',
                'contact_number' => '09060889602',
                'birth_date' => '1988-04-19',
                'gender' => 'male',
                'address' => 'Parañaque City',
                'position' => 'Manager',
                'department' => 'Operations',
                'status' => 'active',
                'access' => 1,
            ],
            [
                'first_name' => 'Yvette Ivy',
                'middle_name' => 'Usman',
                'last_name' => 'Dela Cruz',
                'email' => 'yvetteivydelacruz@gmail.com',
                'contact_number' => '09171739447',
                'birth_date' => '1991-06-02',
                'gender' => 'female',
                'address' => 'B13 L5 Camella Homes Classic Brgy. Don Bosco Parañaque',
                'position' => 'Finance',
                'department' => 'Finance',
                'status' => 'active',
                'access' => 6,
            ],
            [
                'first_name' => 'Normita',
                'middle_name' => 'Maniago',
                'last_name' => 'Alota',
                'email' => 'normita.alota@auls.online',
                'contact_number' => '09614633292',
                'birth_date' => '1990-09-10',
                'gender' => 'female',
                'address' => '505 Tramp St. Corner Protacio Pasay City',
                'position' => 'Finance',
                'department' => 'Finance',
                'status' => 'active',
                'access' => 6,
            ],
            [
                'first_name' => 'Julie-ann',
                'middle_name' => 'Pavericio',
                'last_name' => 'Usman',
                'email' => 'julie-ann.usman@auls.online',
                'contact_number' => '09957789988',
                'birth_date' => '1995-04-26',
                'gender' => 'female',
                'address' => '4716 Cuangco St Pio Del Pilar Makati City',
                'position' => 'HR',
                'department' => 'HR',
                'status' => 'active',
                'access' => 7,
            ],

            // Added / updated POS users
            [
                'first_name' => 'Zidick',
                'middle_name' => 'Panis',
                'last_name' => 'Alvarez',
                'email' => 'zidickpanisalvarez08@gmail.com',
                'contact_number' => '9467599086',
                'birth_date' => '2007-08-08',
                'gender' => 'male',
                'address' => '092 Baloyboy Masin Sur, Candelaria Quezon',
                'position' => 'Waiter',
                'department' => 'Service',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Florentino Jr.',
                'middle_name' => 'Duhaylungsod',
                'last_name' => 'Bustamante',
                'email' => 'florentinobustamante021@gmail.com',
                'contact_number' => '9683653243',
                'birth_date' => '1979-06-26',
                'gender' => 'male',
                'address' => '849 C Quezon Boulevard Sta Cruz Manila',
                'position' => 'Cook',
                'department' => 'Kitchen',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Janzzen Aldrick',
                'middle_name' => 'Soriano',
                'last_name' => 'Ditalo',
                'email' => 'janzzennditalo@gmail.com',
                'contact_number' => '9395153111',
                'birth_date' => '1993-10-15',
                'gender' => 'male',
                'address' => '2377-7 Pasigline St. Santa Ana Manila',
                'position' => 'Cook',
                'department' => 'Kitchen',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Jonh Mark',
                'middle_name' => 'Dioso',
                'last_name' => 'Evangelio',
                'email' => 'evangeliojm26@gmail.com',
                'contact_number' => '9676807952',
                'birth_date' => '1997-01-26',
                'gender' => 'male',
                'address' => '726-B Tandem Bldg. Pres Quirino Avenue Malate Manila',
                'position' => 'Kitchen Helper',
                'department' => 'Kitchen',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Randy',
                'middle_name' => 'Tolentino',
                'last_name' => 'Gunio',
                'email' => 'randygunio01@gmail.com',
                'contact_number' => '9701780377',
                'birth_date' => '1976-11-25',
                'gender' => 'male',
                'address' => '#0539 Quirino Ave. Brgy. San Dionisio, Paranaque City',
                'position' => 'Cook',
                'department' => 'Kitchen',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Mary Grace',
                'middle_name' => 'Blas',
                'last_name' => 'Macaraig',
                'email' => 'macaraigmarygrace717@gmail.com',
                'contact_number' => '9461712136',
                'birth_date' => '2008-02-04',
                'gender' => 'female',
                'address' => '2173 int.9 Maginhawa St. Malate Manila',
                'position' => 'Waitress',
                'department' => 'Service',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Crizelda',
                'middle_name' => 'Manzanal',
                'last_name' => 'Manalo',
                'email' => 'crizeldamanalo@gmail.com',
                'contact_number' => '9358048322',
                'birth_date' => '1983-03-24',
                'gender' => 'female',
                'address' => '21 P. Basilio St. Pasay City',
                'position' => 'Dishwasher',
                'department' => 'Kitchen',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Wilma',
                'middle_name' => 'Agujetas',
                'last_name' => 'Olmoguis',
                'email' => 'wilmaolmoguis@gmail.com',
                'contact_number' => '9513302833',
                'birth_date' => '1985-08-28',
                'gender' => 'female',
                'address' => '#135 David St.Fb Harrison Pasay City',
                'position' => 'Cashier',
                'department' => 'Finance',
                'status' => 'active',
                'access' => 2,
            ],
            [
                'first_name' => 'Rolando Jr.',
                'middle_name' => 'Agujetas',
                'last_name' => 'Olmoguis',
                'email' => 'rolando20olmoguis@gmail.com',
                'contact_number' => '9089854506',
                'birth_date' => '1984-09-14',
                'gender' => 'male',
                'address' => '135 David St. Pasay City',
                'position' => 'Manager/Head Chef',
                'department' => 'Management',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Cyrus',
                'middle_name' => 'Jumawan',
                'last_name' => 'Oyog',
                'email' => 'oycyrus2016@gmail.com',
                'contact_number' => '9305625334',
                'birth_date' => '1987-02-06',
                'gender' => 'male',
                'address' => 'Leveriza St. Brgy. 720 Malate Manila',
                'position' => 'Line Cook',
                'department' => 'Kitchen',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Arjay',
                'middle_name' => null,
                'last_name' => 'Pepito',
                'email' => 'arjaypepito49@gmail.com',
                'contact_number' => '9300496717',
                'birth_date' => '2004-05-16',
                'gender' => 'male',
                'address' => '#0539 Quirino Ave. Brgy. San Dionisio, Paranaque City',
                'position' => 'Helper',
                'department' => 'Kitchen',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Resma',
                'middle_name' => 'Edquila',
                'last_name' => 'Rameses',
                'email' => 'edquilarameses@gmail.com',
                'contact_number' => '9994754450',
                'birth_date' => '1978-05-30',
                'gender' => 'male',
                'address' => '2126 San Andres ext. Sta ana Manila',
                'position' => 'Line Cook',
                'department' => 'Kitchen',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Rosendo Jr.',
                'middle_name' => 'Manuel',
                'last_name' => 'Tugano',
                'email' => 'rosvtugano@gmail.com',
                'contact_number' => '9514920173',
                'birth_date' => '1991-10-18',
                'gender' => 'male',
                'address' => '20-36 FB Harrison David St. Pasay City',
                'position' => 'Cashier/Waiter',
                'department' => 'Service',
                'status' => 'active',
                'access' => 2,
            ],
            [
                'first_name' => 'Rosel',
                'middle_name' => 'Cosio',
                'last_name' => 'Caldeza',
                'email' => 'rosecaldeza96@gmail.com',
                'contact_number' => '9663544509',
                'birth_date' => '1996-11-06',
                'gender' => 'female',
                'address' => 'P. Ocampo St. Vito Cruz Malate Manila',
                'position' => 'Waitress',
                'department' => 'Service',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Criz Henson',
                'middle_name' => 'Checa',
                'last_name' => 'Cortez',
                'email' => 'crizhenzoncheca@gmail.com',
                'contact_number' => '9456695204',
                'birth_date' => '2007-11-06',
                'gender' => 'male',
                'address' => 'INT9 Brgy 714 Maginhawa St Malate Manila',
                'position' => 'Kitchen Helper',
                'department' => 'Kitchen',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Richlyn',
                'middle_name' => 'Otayde',
                'last_name' => 'Libanan',
                'email' => 'richlynlibanan2525@gmail.com',
                'contact_number' => '9659701814',
                'birth_date' => '2006-05-30',
                'gender' => 'female',
                'address' => '2166 Taft Avenue G. Villanueva Brgy 52 Pasay City',
                'position' => 'Waitress',
                'department' => 'Service',
                'status' => 'active',
                'access' => 5,
            ],
            [
                'first_name' => 'Jessabel',
                'middle_name' => 'Sardon',
                'last_name' => 'Tubaña',
                'email' => 'jessabeltubana29@gmail.com',
                'contact_number' => '9707747431',
                'birth_date' => '1997-03-29',
                'gender' => 'female',
                'address' => '2491 Crisolita St Brgy 767 San Andres Bukid Manila',
                'position' => 'Waitress',
                'department' => 'Service',
                'status' => 'active',
                'access' => 5,
            ],

            // dummy accounts
            [
                'first_name' => 'Frontdoor',
                'middle_name' => 'Frontdoor',
                'last_name' => 'Frontdoor',
                'email' => 'f@pos.com',
                'contact_number' => '09123456789',
                'birth_date' => '1986-09-09',
                'gender' => 'male',
                'address' => 'Dummy Address Only',
                'position' => 'Frontdoor',
                'department' => 'Operations',
                'status' => 'active',
                'access' => 3,
            ],
            [
                'first_name' => 'Cashier',
                'middle_name' => 'Cashier',
                'last_name' => 'Cashier',
                'email' => 'c@pos.com',
                'contact_number' => '09123456789',
                'birth_date' => '1986-12-09',
                'gender' => 'male',
                'address' => 'Dummy Address Only',
                'position' => 'Cashier',
                'department' => 'Finance',
                'status' => 'active',
                'access' => 2,
            ],
        ];

        $hireDateStart = Carbon::create(2026, 3, 8);

        foreach ($employees as $index => $data) {
            $employee = Employee::create([
                'employee_code' => 'EMP' . str_pad($index + 1, 4, '0', STR_PAD_LEFT),
                'first_name' => $data['first_name'],
                'middle_name' => $data['middle_name'],
                'last_name' => $data['last_name'],
                'email' => $data['email'],
                'contact_number' => $data['contact_number'],
                'birth_date' => $data['birth_date'],
                'gender' => $data['gender'],
                'address' => $data['address'],
                'status' => $data['status'],
                'access' => $data['access'],
            ]);

            $middleInitial = !empty($data['middle_name']) ? strtoupper(substr($data['middle_name'], 0, 1)) : '';
            $lastInitial   = !empty($data['last_name']) ? strtoupper(substr($data['last_name'], 0, 1)) : '';
            $initials = $middleInitial . $lastInitial;

            $username = strtolower(str_replace(' ', '', $data['first_name']) . $initials) . '@pos.com';

            $employee->user()->create([
                'name' => trim($data['first_name'] . ' ' . $data['middle_name'] . ' ' . $data['last_name']),
                'email' => $username,
                'password' => Hash::make('1'),
                'role' => $data['access'],
            ]);

            EmploymentDetail::create([
                'employee_id' => $employee->id,
                'position' => $data['position'],
                'department' => $data['department'],
                'hire_date' => $hireDateStart->copy()->addDays($index)->format('Y-m-d'),
                'salary' => rand(20000, 40000),
                'daily_rate' => rand(800, 1500),
                'employment_type' => rand(0, 1) ? 'regular' : 'contractual',
            ]);
        }
    }
}