<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RouteSeeder extends Seeder
{
    public function run(): void
    {
        $routes = [
            // Shared
            ['route_name' => 'Dashboard', 'route' => 'dashboard'],
            ['route_name' => 'Profile Edit', 'route' => 'profile.edit'],
            ['route_name' => 'Profile Update', 'route' => 'profile.update'],
            ['route_name' => 'Profile Destroy', 'route' => 'profile.destroy'],

            // Cashier
            ['route_name' => 'Cashier POS', 'route' => 'cashier.pos'],
            ['route_name' => 'Cashier Table Sessions', 'route' => 'cashier.table_sessions'],
            ['route_name' => 'Cashier POS Items', 'route' => 'cashier.pos-items'],
            ['route_name' => 'Cashier Verify Voucher', 'route' => 'cashier.pos.verify-voucher'],
            ['route_name' => 'Cashier Verify Manager Password', 'route' => 'cashier.verify-manager-password'],
            ['route_name' => 'Cashier Orders', 'route' => 'cashier.orders'],
            ['route_name' => 'Cashier Orders Fetch Filtered', 'route' => 'cashier.orders.fetch-filtered-orders'],
            ['route_name' => 'Cashier Orders Store', 'route' => 'cashier.orders.store'],
            ['route_name' => 'Cashier Orders Cancel', 'route' => 'cashier.orders.cancel'],
            ['route_name' => 'Cashier Orders PDF', 'route' => 'cashier.orders.pdf'],
            ['route_name' => 'Cashier Orders Store Items', 'route' => 'cashier.orders.store-items'],
            ['route_name' => 'Cashier Orders Cancel Item', 'route' => 'cashier.orders.cancel_item'],
            ['route_name' => 'Cashier Orders Refresh Computation', 'route' => 'cashier.orders.refresh-computation'],
            ['route_name' => 'Cashier Orders Store Leftover', 'route' => 'cashier.orders.store-leftover'],
            ['route_name' => 'Cashier Orders Table Session Addons Store', 'route' => 'cashier.orders.table_session_addons.store'],
            ['route_name' => 'Cashier Orders Table Session Addons Void', 'route' => 'cashier.orders.table_session_addons.void'],
            ['route_name' => 'Cashier Menus', 'route' => 'cashier.menus'],
            ['route_name' => 'Cashier Menus Edit', 'route' => 'cashier.menus.edit'],
            ['route_name' => 'Cashier Menus Store', 'route' => 'cashier.menus.store'],
            ['route_name' => 'Cashier Reports', 'route' => 'cashier.reports'],
            ['route_name' => 'Cashier Expenses', 'route' => 'cashier.expenses'],
            ['route_name' => 'Cashier Expenses Fetch Filtered', 'route' => 'cashier.expenses.fetch-filtered-expenses'],
            ['route_name' => 'Cashier Expenses Store', 'route' => 'cashier.expenses.store'],
            ['route_name' => 'Cashier Table Occupancies', 'route' => 'cashier.table_occupancies'],
            ['route_name' => 'Cashier Table Admission', 'route' => 'cashier.table_admission'],
            ['route_name' => 'Cashier Table Occupancies Assign', 'route' => 'cashier.table_occupancies.assign'],
            ['route_name' => 'Cashier Table Occupancies Update', 'route' => 'cashier.table_occupancies.update'],
            ['route_name' => 'Cashier Table Occupancies Cancel', 'route' => 'cashier.table_occupancies.cancel'],
            ['route_name' => 'Cashier Table Admission Assign', 'route' => 'cashier.table_admission.assign'],
            ['route_name' => 'Cashier Reservations Index', 'route' => 'cashier.reservations.index'],
            ['route_name' => 'Cashier Reservations Create', 'route' => 'cashier.reservations.create'],
            ['route_name' => 'Cashier Reservations Store', 'route' => 'cashier.reservations.store'],
            ['route_name' => 'Cashier Reservations Show', 'route' => 'cashier.reservations.show'],
            ['route_name' => 'Cashier Reservations Edit', 'route' => 'cashier.reservations.edit'],
            ['route_name' => 'Cashier Reservations Update', 'route' => 'cashier.reservations.update'],
            ['route_name' => 'Cashier Reservations Destroy', 'route' => 'cashier.reservations.destroy'],
            ['route_name' => 'Cashier Inventory', 'route' => 'cashier.inventory'],
            ['route_name' => 'Cashier Inventory Items', 'route' => 'cashier.inventory.items'],
            ['route_name' => 'Cashier Inventory Items Store', 'route' => 'cashier.inventory.items.store'],
            ['route_name' => 'Cashier Inventory Stock In', 'route' => 'cashier.inventory.stock-in'],
            ['route_name' => 'Cashier Inventory Stock Out', 'route' => 'cashier.inventory.stock-out'],
            ['route_name' => 'Cashier Inventory Categories', 'route' => 'cashier.inventory.categories'],
            ['route_name' => 'Cashier Inventory Categories Store', 'route' => 'cashier.inventory.categories.store'],
            ['route_name' => 'Cashier Inventory General Report', 'route' => 'cashier.inventory.general-report'],
            ['route_name' => 'Cashier Employees Index', 'route' => 'cashier.employees.index'],
            ['route_name' => 'Cashier Employees Store', 'route' => 'cashier.employees.store'],
            ['route_name' => 'Cashier Employees Edit', 'route' => 'cashier.employees.edit'],
            ['route_name' => 'Cashier Employment Edit', 'route' => 'cashier.employment.edit'],
            ['route_name' => 'Cashier Employees Schedules Store', 'route' => 'cashier.employees.schedules.store'],
            ['route_name' => 'Cashier Employees Schedules Batch Store', 'route' => 'cashier.employees.schedules.batchStore'],
            ['route_name' => 'Cashier Employees Schedules Update', 'route' => 'cashier.employees.schedules.update'],
            ['route_name' => 'Cashier Employees Schedule', 'route' => 'cashier.employees.schedule'],
            ['route_name' => 'Cashier Employees Schedules Print', 'route' => 'cashier.employees.schedules.print'],
            ['route_name' => 'Cashier Employees Schedules Print All', 'route' => 'cashier.employees.schedules.printAll'],
            ['route_name' => 'Cashier Employment Update', 'route' => 'cashier.employment.update'],
            ['route_name' => 'Cashier Employment Documents Upload', 'route' => 'cashier.employment.documents.upload'],
            ['route_name' => 'Cashier Employees DTR', 'route' => 'cashier.employees.dtr'],
            ['route_name' => 'Cashier Employees DTR Update', 'route' => 'cashier.employees.dtr.update'],
            ['route_name' => 'Cashier Employees Payroll Attendance PDF', 'route' => 'cashier.employees.payroll.attendance.pdf'],
            ['route_name' => 'Cashier Generate Payroll', 'route' => 'cashier.generate-payroll'],
            ['route_name' => 'Cashier Payroll Summary', 'route' => 'cashier.payroll.summary'],
            ['route_name' => 'Cashier Payroll Post', 'route' => 'cashier.payroll.post'],
            ['route_name' => 'Cashier Payroll Index', 'route' => 'cashier.payroll.index'],
            ['route_name' => 'Cashier Payroll View Details', 'route' => 'cashier.payroll.view-payroll-details'],
            ['route_name' => 'Cashier Payroll Deduction Post', 'route' => 'cashier.payroll.deduction.post'],
            ['route_name' => 'Cashier Payroll Payslip Print Single', 'route' => 'cashier.payroll.payslip.print.single'],
            ['route_name' => 'Cashier Payroll Payslip Print Selected', 'route' => 'cashier.payroll.payslip.print.selected'],
            ['route_name' => 'Cashier Payroll Summary Print', 'route' => 'cashier.payroll.summary.print'],
            ['route_name' => 'Cashier Vouchers Index', 'route' => 'cashier.vouchers.index'],
            ['route_name' => 'Cashier Vouchers Store', 'route' => 'cashier.vouchers.store'],
            ['route_name' => 'Cashier Vouchers Update', 'route' => 'cashier.vouchers.update'],
            ['route_name' => 'Cashier Vouchers Destroy', 'route' => 'cashier.vouchers.destroy'],
            ['route_name' => 'Cashier Vouchers Print', 'route' => 'cashier.vouchers.print'],
            ['route_name' => 'Cashier Vouchers Print All', 'route' => 'cashier.vouchers.printAll'],
            ['route_name' => 'Cashier Petty Cashes', 'route' => 'cashier.petty-cashes'],
            ['route_name' => 'Cashier Petty Cashes Store', 'route' => 'cashier.petty-cashes.store'],
            ['route_name' => 'Cashier Petty Cashes Details Store', 'route' => 'cashier.petty-cashes.details.store'],
            ['route_name' => 'Cashier Head Pricing Rules Index', 'route' => 'cashier.head-pricing-rules.index'],
            ['route_name' => 'Cashier Head Pricing Rules Store', 'route' => 'cashier.head-pricing-rules.store'],
            ['route_name' => 'Cashier Head Pricing Rules Update', 'route' => 'cashier.head-pricing-rules.update'],
            ['route_name' => 'Cashier Head Pricing Rules Destroy', 'route' => 'cashier.head-pricing-rules.destroy'],
            ['route_name' => 'Cashier Pricing Schemes Store', 'route' => 'cashier.pricing-schemes.store'],
            ['route_name' => 'Cashier Pricing Schemes Update', 'route' => 'cashier.pricing-schemes.update'],
            ['route_name' => 'Cashier Inventory Report Index', 'route' => 'cashier.inventory.report.index'],
            ['route_name' => 'Cashier Inventory Fetch Report', 'route' => 'cashier.inventory.fetch-inventory-report'],
            ['route_name' => 'Cashier Inventory Print Report PDF', 'route' => 'cashier.inventory.print-inventory-report-pdf'],
            ['route_name' => 'Cashier Expenses Report Index', 'route' => 'cashier.expenses.report.index'],
            ['route_name' => 'Cashier Expenses Fetch Report', 'route' => 'cashier.expenses.fetch-expense-report'],
            ['route_name' => 'Cashier Expenses Print Report PDF', 'route' => 'cashier.expenses.print-expense-report-pdf'],
            ['route_name' => 'Cashier Sales Report Index', 'route' => 'cashier.sales.report.index'],
            ['route_name' => 'Cashier Sales Fetch Report', 'route' => 'cashier.sales.fetch-sales-report'],
            ['route_name' => 'Cashier Sales Print Report PDF', 'route' => 'cashier.sales.print-sales-report-pdf'],
            ['route_name' => 'Cashier My Records', 'route' => 'cashier.myrecords'],
            ['route_name' => 'Cashier Clock In', 'route' => 'cashier.clockin'],
            ['route_name' => 'Cashier Clock Out', 'route' => 'cashier.clockout'],
            ['route_name' => 'Cashier Overtimes Store', 'route' => 'cashier.overtimes.store'],
            ['route_name' => 'Cashier Employees Overtimes', 'route' => 'cashier.employees.overtimes'],
            ['route_name' => 'Cashier Overtimes Filter', 'route' => 'cashier.overtimes.filter'],
            ['route_name' => 'Cashier Overtimes Update Status', 'route' => 'cashier.overtimes.update-status'],

            // Manager
            ['route_name' => 'Manager POS', 'route' => 'manager.pos'],
            ['route_name' => 'Manager Table Sessions', 'route' => 'manager.table_sessions'],
            ['route_name' => 'Manager POS Items', 'route' => 'manager.pos-items'],
            ['route_name' => 'Manager Verify Voucher', 'route' => 'manager.pos.verify-voucher'],
            ['route_name' => 'Manager Verify Manager Password', 'route' => 'manager.verify-manager-password'],
            ['route_name' => 'Manager Orders', 'route' => 'manager.orders'],
            ['route_name' => 'Manager Orders Fetch Filtered', 'route' => 'manager.orders.fetch-filtered-orders'],
            ['route_name' => 'Manager Orders Store', 'route' => 'manager.orders.store'],
            ['route_name' => 'Manager Orders Cancel', 'route' => 'manager.orders.cancel'],
            ['route_name' => 'Manager Orders PDF', 'route' => 'manager.orders.pdf'],
            ['route_name' => 'Manager Orders Store Items', 'route' => 'manager.orders.store-items'],
            ['route_name' => 'Manager Orders Cancel Item', 'route' => 'manager.orders.cancel_item'],
            ['route_name' => 'Manager Orders Refresh Computation', 'route' => 'manager.orders.refresh-computation'],
            ['route_name' => 'Manager Orders Store Leftover', 'route' => 'manager.orders.store-leftover'],
            ['route_name' => 'Manager Orders Table Session Addons Store', 'route' => 'manager.orders.table_session_addons.store'],
            ['route_name' => 'Manager Orders Table Session Addons Void', 'route' => 'manager.orders.table_session_addons.void'],
            ['route_name' => 'Manager Menus', 'route' => 'manager.menus'],
            ['route_name' => 'Manager Menus Edit', 'route' => 'manager.menus.edit'],
            ['route_name' => 'Manager Menus Store', 'route' => 'manager.menus.store'],
            ['route_name' => 'Manager Reports', 'route' => 'manager.reports'],
            ['route_name' => 'Manager Expenses', 'route' => 'manager.expenses'],
            ['route_name' => 'Manager Expenses Fetch Filtered', 'route' => 'manager.expenses.fetch-filtered-expenses'],
            ['route_name' => 'Manager Expenses Store', 'route' => 'manager.expenses.store'],
            ['route_name' => 'Manager Table Occupancies', 'route' => 'manager.table_occupancies'],
            ['route_name' => 'Manager Table Admission', 'route' => 'manager.table_admission'],
            ['route_name' => 'Manager Table Occupancies Assign', 'route' => 'manager.table_occupancies.assign'],
            ['route_name' => 'Manager Table Occupancies Update', 'route' => 'manager.table_occupancies.update'],
            ['route_name' => 'Manager Table Occupancies Cancel', 'route' => 'manager.table_occupancies.cancel'],
            ['route_name' => 'Manager Table Admission Assign', 'route' => 'manager.table_admission.assign'],
            ['route_name' => 'Manager Reservations Index', 'route' => 'manager.reservations.index'],
            ['route_name' => 'Manager Reservations Create', 'route' => 'manager.reservations.create'],
            ['route_name' => 'Manager Reservations Store', 'route' => 'manager.reservations.store'],
            ['route_name' => 'Manager Reservations Show', 'route' => 'manager.reservations.show'],
            ['route_name' => 'Manager Reservations Edit', 'route' => 'manager.reservations.edit'],
            ['route_name' => 'Manager Reservations Update', 'route' => 'manager.reservations.update'],
            ['route_name' => 'Manager Reservations Destroy', 'route' => 'manager.reservations.destroy'],
            ['route_name' => 'Manager Inventory', 'route' => 'manager.inventory'],
            ['route_name' => 'Manager Inventory Items', 'route' => 'manager.inventory.items'],
            ['route_name' => 'Manager Inventory Items Store', 'route' => 'manager.inventory.items.store'],
            ['route_name' => 'Manager Inventory Stock In', 'route' => 'manager.inventory.stock-in'],
            ['route_name' => 'Manager Inventory Stock Out', 'route' => 'manager.inventory.stock-out'],
            ['route_name' => 'Manager Inventory Categories', 'route' => 'manager.inventory.categories'],
            ['route_name' => 'Manager Inventory Categories Store', 'route' => 'manager.inventory.categories.store'],
            ['route_name' => 'Manager Inventory General Report', 'route' => 'manager.inventory.general-report'],
            ['route_name' => 'Manager Employees Index', 'route' => 'manager.employees.index'],
            ['route_name' => 'Manager Employees Store', 'route' => 'manager.employees.store'],
            ['route_name' => 'Manager Employees Edit', 'route' => 'manager.employees.edit'],
            ['route_name' => 'Manager Employment Edit', 'route' => 'manager.employment.edit'],
            ['route_name' => 'Manager Employees Schedules Store', 'route' => 'manager.employees.schedules.store'],
            ['route_name' => 'Manager Employees Schedules Batch Store', 'route' => 'manager.employees.schedules.batchStore'],
            ['route_name' => 'Manager Employees Schedules Update', 'route' => 'manager.employees.schedules.update'],
            ['route_name' => 'Manager Employees Schedule', 'route' => 'manager.employees.schedule'],
            ['route_name' => 'Manager Employees Schedules Print', 'route' => 'manager.employees.schedules.print'],
            ['route_name' => 'Manager Employees Schedules Print All', 'route' => 'manager.employees.schedules.printAll'],
            ['route_name' => 'Manager Employment Update', 'route' => 'manager.employment.update'],
            ['route_name' => 'Manager Employment Documents Upload', 'route' => 'manager.employment.documents.upload'],
            ['route_name' => 'Manager Employees DTR', 'route' => 'manager.employees.dtr'],
            ['route_name' => 'Manager Employees DTR Update', 'route' => 'manager.employees.dtr.update'],
            ['route_name' => 'Manager Employees Payroll Attendance PDF', 'route' => 'manager.employees.payroll.attendance.pdf'],
            ['route_name' => 'Manager Generate Payroll', 'route' => 'manager.generate-payroll'],
            ['route_name' => 'Manager Payroll Summary', 'route' => 'manager.payroll.summary'],
            ['route_name' => 'Manager Payroll Post', 'route' => 'manager.payroll.post'],
            ['route_name' => 'Manager Payroll Index', 'route' => 'manager.payroll.index'],
            ['route_name' => 'Manager Payroll View Details', 'route' => 'manager.payroll.view-payroll-details'],
            ['route_name' => 'Manager Payroll Deduction Post', 'route' => 'manager.payroll.deduction.post'],
            ['route_name' => 'Manager Payroll Payslip Print Single', 'route' => 'manager.payroll.payslip.print.single'],
            ['route_name' => 'Manager Payroll Payslip Print Selected', 'route' => 'manager.payroll.payslip.print.selected'],
            ['route_name' => 'Manager Payroll Summary Print', 'route' => 'manager.payroll.summary.print'],
            ['route_name' => 'Manager Vouchers Index', 'route' => 'manager.vouchers.index'],
            ['route_name' => 'Manager Vouchers Store', 'route' => 'manager.vouchers.store'],
            ['route_name' => 'Manager Vouchers Update', 'route' => 'manager.vouchers.update'],
            ['route_name' => 'Manager Vouchers Destroy', 'route' => 'manager.vouchers.destroy'],
            ['route_name' => 'Manager Vouchers Print', 'route' => 'manager.vouchers.print'],
            ['route_name' => 'Manager Vouchers Print All', 'route' => 'manager.vouchers.printAll'],
            ['route_name' => 'Manager Petty Cashes', 'route' => 'manager.petty-cashes'],
            ['route_name' => 'Manager Petty Cashes Store', 'route' => 'manager.petty-cashes.store'],
            ['route_name' => 'Manager Petty Cashes Details Store', 'route' => 'manager.petty-cashes.details.store'],
            ['route_name' => 'Manager Head Pricing Rules Index', 'route' => 'manager.head-pricing-rules.index'],
            ['route_name' => 'Manager Head Pricing Rules Store', 'route' => 'manager.head-pricing-rules.store'],
            ['route_name' => 'Manager Head Pricing Rules Update', 'route' => 'manager.head-pricing-rules.update'],
            ['route_name' => 'Manager Head Pricing Rules Destroy', 'route' => 'manager.head-pricing-rules.destroy'],
            ['route_name' => 'Manager Pricing Schemes Store', 'route' => 'manager.pricing-schemes.store'],
            ['route_name' => 'Manager Pricing Schemes Update', 'route' => 'manager.pricing-schemes.update'],
            ['route_name' => 'Manager Inventory Report Index', 'route' => 'manager.inventory.report.index'],
            ['route_name' => 'Manager Inventory Fetch Report', 'route' => 'manager.inventory.fetch-inventory-report'],
            ['route_name' => 'Manager Inventory Print Report PDF', 'route' => 'manager.inventory.print-inventory-report-pdf'],
            ['route_name' => 'Manager Expenses Report Index', 'route' => 'manager.expenses.report.index'],
            ['route_name' => 'Manager Expenses Fetch Report', 'route' => 'manager.expenses.fetch-expense-report'],
            ['route_name' => 'Manager Expenses Print Report PDF', 'route' => 'manager.expenses.print-expense-report-pdf'],
            ['route_name' => 'Manager Sales Report Index', 'route' => 'manager.sales.report.index'],
            ['route_name' => 'Manager Sales Fetch Report', 'route' => 'manager.sales.fetch-sales-report'],
            ['route_name' => 'Manager Sales Print Report PDF', 'route' => 'manager.sales.print-sales-report-pdf'],
            ['route_name' => 'Manager My Records', 'route' => 'manager.myrecords'],
            ['route_name' => 'Manager Clock In', 'route' => 'manager.clockin'],
            ['route_name' => 'Manager Clock Out', 'route' => 'manager.clockout'],
            ['route_name' => 'Manager Overtimes Store', 'route' => 'manager.overtimes.store'],
            ['route_name' => 'Manager Employees Overtimes', 'route' => 'manager.employees.overtimes'],
            ['route_name' => 'Manager Overtimes Filter', 'route' => 'manager.overtimes.filter'],
            ['route_name' => 'Manager Overtimes Update Status', 'route' => 'manager.overtimes.update-status'],

            // Frontdoor
            ['route_name' => 'Frontdoor POS', 'route' => 'frontdoor.pos'],
            ['route_name' => 'Frontdoor Table Sessions', 'route' => 'frontdoor.table_sessions'],
            ['route_name' => 'Frontdoor POS Items', 'route' => 'frontdoor.pos-items'],
            ['route_name' => 'Frontdoor Verify Voucher', 'route' => 'frontdoor.pos.verify-voucher'],
            ['route_name' => 'Frontdoor Verify Manager Password', 'route' => 'frontdoor.verify-manager-password'],
            ['route_name' => 'Frontdoor Orders', 'route' => 'frontdoor.orders'],
            ['route_name' => 'Frontdoor Orders Fetch Filtered', 'route' => 'frontdoor.orders.fetch-filtered-orders'],
            ['route_name' => 'Frontdoor Orders Store', 'route' => 'frontdoor.orders.store'],
            ['route_name' => 'Frontdoor Orders Cancel', 'route' => 'frontdoor.orders.cancel'],
            ['route_name' => 'Frontdoor Orders PDF', 'route' => 'frontdoor.orders.pdf'],
            ['route_name' => 'Frontdoor Orders Store Items', 'route' => 'frontdoor.orders.store-items'],
            ['route_name' => 'Frontdoor Orders Cancel Item', 'route' => 'frontdoor.orders.cancel_item'],
            ['route_name' => 'Frontdoor Orders Refresh Computation', 'route' => 'frontdoor.orders.refresh-computation'],
            ['route_name' => 'Frontdoor Orders Store Leftover', 'route' => 'frontdoor.orders.store-leftover'],
            ['route_name' => 'Frontdoor Orders Table Session Addons Store', 'route' => 'frontdoor.orders.table_session_addons.store'],
            ['route_name' => 'Frontdoor Orders Table Session Addons Void', 'route' => 'frontdoor.orders.table_session_addons.void'],
            ['route_name' => 'Frontdoor Menus', 'route' => 'frontdoor.menus'],
            ['route_name' => 'Frontdoor Menus Edit', 'route' => 'frontdoor.menus.edit'],
            ['route_name' => 'Frontdoor Menus Store', 'route' => 'frontdoor.menus.store'],
            ['route_name' => 'Frontdoor Reports', 'route' => 'frontdoor.reports'],
            ['route_name' => 'Frontdoor Expenses', 'route' => 'frontdoor.expenses'],
            ['route_name' => 'Frontdoor Expenses Fetch Filtered', 'route' => 'frontdoor.expenses.fetch-filtered-expenses'],
            ['route_name' => 'Frontdoor Expenses Store', 'route' => 'frontdoor.expenses.store'],
            ['route_name' => 'Frontdoor Table Occupancies', 'route' => 'frontdoor.table_occupancies'],
            ['route_name' => 'Frontdoor Table Admission', 'route' => 'frontdoor.table_admission'],
            ['route_name' => 'Frontdoor Table Occupancies Assign', 'route' => 'frontdoor.table_occupancies.assign'],
            ['route_name' => 'Frontdoor Table Occupancies Update', 'route' => 'frontdoor.table_occupancies.update'],
            ['route_name' => 'Frontdoor Table Occupancies Cancel', 'route' => 'frontdoor.table_occupancies.cancel'],
            ['route_name' => 'Frontdoor Table Admission Assign', 'route' => 'frontdoor.table_admission.assign'],
            ['route_name' => 'Frontdoor Reservations Index', 'route' => 'frontdoor.reservations.index'],
            ['route_name' => 'Frontdoor Reservations Create', 'route' => 'frontdoor.reservations.create'],
            ['route_name' => 'Frontdoor Reservations Store', 'route' => 'frontdoor.reservations.store'],
            ['route_name' => 'Frontdoor Reservations Show', 'route' => 'frontdoor.reservations.show'],
            ['route_name' => 'Frontdoor Reservations Edit', 'route' => 'frontdoor.reservations.edit'],
            ['route_name' => 'Frontdoor Reservations Update', 'route' => 'frontdoor.reservations.update'],
            ['route_name' => 'Frontdoor Reservations Destroy', 'route' => 'frontdoor.reservations.destroy'],
            ['route_name' => 'Frontdoor Inventory', 'route' => 'frontdoor.inventory'],
            ['route_name' => 'Frontdoor Inventory Items', 'route' => 'frontdoor.inventory.items'],
            ['route_name' => 'Frontdoor Inventory Items Store', 'route' => 'frontdoor.inventory.items.store'],
            ['route_name' => 'Frontdoor Inventory Stock In', 'route' => 'frontdoor.inventory.stock-in'],
            ['route_name' => 'Frontdoor Inventory Stock Out', 'route' => 'frontdoor.inventory.stock-out'],
            ['route_name' => 'Frontdoor Inventory Categories', 'route' => 'frontdoor.inventory.categories'],
            ['route_name' => 'Frontdoor Inventory Categories Store', 'route' => 'frontdoor.inventory.categories.store'],
            ['route_name' => 'Frontdoor Inventory General Report', 'route' => 'frontdoor.inventory.general-report'],
            ['route_name' => 'Frontdoor Employees Index', 'route' => 'frontdoor.employees.index'],
            ['route_name' => 'Frontdoor Employees Store', 'route' => 'frontdoor.employees.store'],
            ['route_name' => 'Frontdoor Employees Edit', 'route' => 'frontdoor.employees.edit'],
            ['route_name' => 'Frontdoor Employment Edit', 'route' => 'frontdoor.employment.edit'],
            ['route_name' => 'Frontdoor Employees Schedules Store', 'route' => 'frontdoor.employees.schedules.store'],
            ['route_name' => 'Frontdoor Employees Schedules Batch Store', 'route' => 'frontdoor.employees.schedules.batchStore'],
            ['route_name' => 'Frontdoor Employees Schedules Update', 'route' => 'frontdoor.employees.schedules.update'],
            ['route_name' => 'Frontdoor Employees Schedule', 'route' => 'frontdoor.employees.schedule'],
            ['route_name' => 'Frontdoor Employees Schedules Print', 'route' => 'frontdoor.employees.schedules.print'],
            ['route_name' => 'Frontdoor Employees Schedules Print All', 'route' => 'frontdoor.employees.schedules.printAll'],
            ['route_name' => 'Frontdoor Employment Update', 'route' => 'frontdoor.employment.update'],
            ['route_name' => 'Frontdoor Employment Documents Upload', 'route' => 'frontdoor.employment.documents.upload'],
            ['route_name' => 'Frontdoor Employees DTR', 'route' => 'frontdoor.employees.dtr'],
            ['route_name' => 'Frontdoor Employees DTR Update', 'route' => 'frontdoor.employees.dtr.update'],
            ['route_name' => 'Frontdoor Employees Payroll Attendance PDF', 'route' => 'frontdoor.employees.payroll.attendance.pdf'],
            ['route_name' => 'Frontdoor Generate Payroll', 'route' => 'frontdoor.generate-payroll'],
            ['route_name' => 'Frontdoor Payroll Summary', 'route' => 'frontdoor.payroll.summary'],
            ['route_name' => 'Frontdoor Payroll Post', 'route' => 'frontdoor.payroll.post'],
            ['route_name' => 'Frontdoor Payroll Index', 'route' => 'frontdoor.payroll.index'],
            ['route_name' => 'Frontdoor Payroll View Details', 'route' => 'frontdoor.payroll.view-payroll-details'],
            ['route_name' => 'Frontdoor Payroll Deduction Post', 'route' => 'frontdoor.payroll.deduction.post'],
            ['route_name' => 'Frontdoor Payroll Payslip Print Single', 'route' => 'frontdoor.payroll.payslip.print.single'],
            ['route_name' => 'Frontdoor Payroll Payslip Print Selected', 'route' => 'frontdoor.payroll.payslip.print.selected'],
            ['route_name' => 'Frontdoor Payroll Summary Print', 'route' => 'frontdoor.payroll.summary.print'],
            ['route_name' => 'Frontdoor Vouchers Index', 'route' => 'frontdoor.vouchers.index'],
            ['route_name' => 'Frontdoor Vouchers Store', 'route' => 'frontdoor.vouchers.store'],
            ['route_name' => 'Frontdoor Vouchers Update', 'route' => 'frontdoor.vouchers.update'],
            ['route_name' => 'Frontdoor Vouchers Destroy', 'route' => 'frontdoor.vouchers.destroy'],
            ['route_name' => 'Frontdoor Vouchers Print', 'route' => 'frontdoor.vouchers.print'],
            ['route_name' => 'Frontdoor Vouchers Print All', 'route' => 'frontdoor.vouchers.printAll'],
            ['route_name' => 'Frontdoor Petty Cashes', 'route' => 'frontdoor.petty-cashes'],
            ['route_name' => 'Frontdoor Petty Cashes Store', 'route' => 'frontdoor.petty-cashes.store'],
            ['route_name' => 'Frontdoor Petty Cashes Details Store', 'route' => 'frontdoor.petty-cashes.details.store'],
            ['route_name' => 'Frontdoor Head Pricing Rules Index', 'route' => 'frontdoor.head-pricing-rules.index'],
            ['route_name' => 'Frontdoor Head Pricing Rules Store', 'route' => 'frontdoor.head-pricing-rules.store'],
            ['route_name' => 'Frontdoor Head Pricing Rules Update', 'route' => 'frontdoor.head-pricing-rules.update'],
            ['route_name' => 'Frontdoor Head Pricing Rules Destroy', 'route' => 'frontdoor.head-pricing-rules.destroy'],
            ['route_name' => 'Frontdoor Pricing Schemes Store', 'route' => 'frontdoor.pricing-schemes.store'],
            ['route_name' => 'Frontdoor Pricing Schemes Update', 'route' => 'frontdoor.pricing-schemes.update'],
            ['route_name' => 'Frontdoor Inventory Report Index', 'route' => 'frontdoor.inventory.report.index'],
            ['route_name' => 'Frontdoor Inventory Fetch Report', 'route' => 'frontdoor.inventory.fetch-inventory-report'],
            ['route_name' => 'Frontdoor Inventory Print Report PDF', 'route' => 'frontdoor.inventory.print-inventory-report-pdf'],
            ['route_name' => 'Frontdoor Expenses Report Index', 'route' => 'frontdoor.expenses.report.index'],
            ['route_name' => 'Frontdoor Expenses Fetch Report', 'route' => 'frontdoor.expenses.fetch-expense-report'],
            ['route_name' => 'Frontdoor Expenses Print Report PDF', 'route' => 'frontdoor.expenses.print-expense-report-pdf'],
            ['route_name' => 'Frontdoor Sales Report Index', 'route' => 'frontdoor.sales.report.index'],
            ['route_name' => 'Frontdoor Sales Fetch Report', 'route' => 'frontdoor.sales.fetch-sales-report'],
            ['route_name' => 'Frontdoor Sales Print Report PDF', 'route' => 'frontdoor.sales.print-sales-report-pdf'],
            ['route_name' => 'Frontdoor My Records', 'route' => 'frontdoor.myrecords'],
            ['route_name' => 'Frontdoor Clock In', 'route' => 'frontdoor.clockin'],
            ['route_name' => 'Frontdoor Clock Out', 'route' => 'frontdoor.clockout'],
            ['route_name' => 'Frontdoor Overtimes Store', 'route' => 'frontdoor.overtimes.store'],
            ['route_name' => 'Frontdoor Employees Overtimes', 'route' => 'frontdoor.employees.overtimes'],
            ['route_name' => 'Frontdoor Overtimes Filter', 'route' => 'frontdoor.overtimes.filter'],
            ['route_name' => 'Frontdoor Overtimes Update Status', 'route' => 'frontdoor.overtimes.update-status'],

            // Purchaser
            ['route_name' => 'Purchaser POS', 'route' => 'purchaser.pos'],
            ['route_name' => 'Purchaser Table Sessions', 'route' => 'purchaser.table_sessions'],
            ['route_name' => 'Purchaser POS Items', 'route' => 'purchaser.pos-items'],
            ['route_name' => 'Purchaser Verify Voucher', 'route' => 'purchaser.pos.verify-voucher'],
            ['route_name' => 'Purchaser Verify Manager Password', 'route' => 'purchaser.verify-manager-password'],
            ['route_name' => 'Purchaser Orders', 'route' => 'purchaser.orders'],
            ['route_name' => 'Purchaser Orders Fetch Filtered', 'route' => 'purchaser.orders.fetch-filtered-orders'],
            ['route_name' => 'Purchaser Orders Store', 'route' => 'purchaser.orders.store'],
            ['route_name' => 'Purchaser Orders Cancel', 'route' => 'purchaser.orders.cancel'],
            ['route_name' => 'Purchaser Orders PDF', 'route' => 'purchaser.orders.pdf'],
            ['route_name' => 'Purchaser Orders Store Items', 'route' => 'purchaser.orders.store-items'],
            ['route_name' => 'Purchaser Orders Cancel Item', 'route' => 'purchaser.orders.cancel_item'],
            ['route_name' => 'Purchaser Orders Refresh Computation', 'route' => 'purchaser.orders.refresh-computation'],
            ['route_name' => 'Purchaser Orders Store Leftover', 'route' => 'purchaser.orders.store-leftover'],
            ['route_name' => 'Purchaser Orders Table Session Addons Store', 'route' => 'purchaser.orders.table_session_addons.store'],
            ['route_name' => 'Purchaser Orders Table Session Addons Void', 'route' => 'purchaser.orders.table_session_addons.void'],
            ['route_name' => 'Purchaser Menus', 'route' => 'purchaser.menus'],
            ['route_name' => 'Purchaser Menus Edit', 'route' => 'purchaser.menus.edit'],
            ['route_name' => 'Purchaser Menus Store', 'route' => 'purchaser.menus.store'],
            ['route_name' => 'Purchaser Reports', 'route' => 'purchaser.reports'],
            ['route_name' => 'Purchaser Expenses', 'route' => 'purchaser.expenses'],
            ['route_name' => 'Purchaser Expenses Fetch Filtered', 'route' => 'purchaser.expenses.fetch-filtered-expenses'],
            ['route_name' => 'Purchaser Expenses Store', 'route' => 'purchaser.expenses.store'],
            ['route_name' => 'Purchaser Table Occupancies', 'route' => 'purchaser.table_occupancies'],
            ['route_name' => 'Purchaser Table Admission', 'route' => 'purchaser.table_admission'],
            ['route_name' => 'Purchaser Table Occupancies Assign', 'route' => 'purchaser.table_occupancies.assign'],
            ['route_name' => 'Purchaser Table Occupancies Update', 'route' => 'purchaser.table_occupancies.update'],
            ['route_name' => 'Purchaser Table Occupancies Cancel', 'route' => 'purchaser.table_occupancies.cancel'],
            ['route_name' => 'Purchaser Table Admission Assign', 'route' => 'purchaser.table_admission.assign'],
            ['route_name' => 'Purchaser Reservations Index', 'route' => 'purchaser.reservations.index'],
            ['route_name' => 'Purchaser Reservations Create', 'route' => 'purchaser.reservations.create'],
            ['route_name' => 'Purchaser Reservations Store', 'route' => 'purchaser.reservations.store'],
            ['route_name' => 'Purchaser Reservations Show', 'route' => 'purchaser.reservations.show'],
            ['route_name' => 'Purchaser Reservations Edit', 'route' => 'purchaser.reservations.edit'],
            ['route_name' => 'Purchaser Reservations Update', 'route' => 'purchaser.reservations.update'],
            ['route_name' => 'Purchaser Reservations Destroy', 'route' => 'purchaser.reservations.destroy'],
            ['route_name' => 'Purchaser Inventory', 'route' => 'purchaser.inventory'],
            ['route_name' => 'Purchaser Inventory Items', 'route' => 'purchaser.inventory.items'],
            ['route_name' => 'Purchaser Inventory Items Store', 'route' => 'purchaser.inventory.items.store'],
            ['route_name' => 'Purchaser Inventory Stock In', 'route' => 'purchaser.inventory.stock-in'],
            ['route_name' => 'Purchaser Inventory Stock Out', 'route' => 'purchaser.inventory.stock-out'],
            ['route_name' => 'Purchaser Inventory Categories', 'route' => 'purchaser.inventory.categories'],
            ['route_name' => 'Purchaser Inventory Categories Store', 'route' => 'purchaser.inventory.categories.store'],
            ['route_name' => 'Purchaser Inventory General Report', 'route' => 'purchaser.inventory.general-report'],
            ['route_name' => 'Purchaser Employees Index', 'route' => 'purchaser.employees.index'],
            ['route_name' => 'Purchaser Employees Store', 'route' => 'purchaser.employees.store'],
            ['route_name' => 'Purchaser Employees Edit', 'route' => 'purchaser.employees.edit'],
            ['route_name' => 'Purchaser Employment Edit', 'route' => 'purchaser.employment.edit'],
            ['route_name' => 'Purchaser Employees Schedules Store', 'route' => 'purchaser.employees.schedules.store'],
            ['route_name' => 'Purchaser Employees Schedules Batch Store', 'route' => 'purchaser.employees.schedules.batchStore'],
            ['route_name' => 'Purchaser Employees Schedules Update', 'route' => 'purchaser.employees.schedules.update'],
            ['route_name' => 'Purchaser Employees Schedule', 'route' => 'purchaser.employees.schedule'],
            ['route_name' => 'Purchaser Employees Schedules Print', 'route' => 'purchaser.employees.schedules.print'],
            ['route_name' => 'Purchaser Employees Schedules Print All', 'route' => 'purchaser.employees.schedules.printAll'],
            ['route_name' => 'Purchaser Employment Update', 'route' => 'purchaser.employment.update'],
            ['route_name' => 'Purchaser Employment Documents Upload', 'route' => 'purchaser.employment.documents.upload'],
            ['route_name' => 'Purchaser Employees DTR', 'route' => 'purchaser.employees.dtr'],
            ['route_name' => 'Purchaser Employees DTR Update', 'route' => 'purchaser.employees.dtr.update'],
            ['route_name' => 'Purchaser Employees Payroll Attendance PDF', 'route' => 'purchaser.employees.payroll.attendance.pdf'],
            ['route_name' => 'Purchaser Generate Payroll', 'route' => 'purchaser.generate-payroll'],
            ['route_name' => 'Purchaser Payroll Summary', 'route' => 'purchaser.payroll.summary'],
            ['route_name' => 'Purchaser Payroll Post', 'route' => 'purchaser.payroll.post'],
            ['route_name' => 'Purchaser Payroll Index', 'route' => 'purchaser.payroll.index'],
            ['route_name' => 'Purchaser Payroll View Details', 'route' => 'purchaser.payroll.view-payroll-details'],
            ['route_name' => 'Purchaser Payroll Deduction Post', 'route' => 'purchaser.payroll.deduction.post'],
            ['route_name' => 'Purchaser Payroll Payslip Print Single', 'route' => 'purchaser.payroll.payslip.print.single'],
            ['route_name' => 'Purchaser Payroll Payslip Print Selected', 'route' => 'purchaser.payroll.payslip.print.selected'],
            ['route_name' => 'Purchaser Payroll Summary Print', 'route' => 'purchaser.payroll.summary.print'],
            ['route_name' => 'Purchaser Vouchers Index', 'route' => 'purchaser.vouchers.index'],
            ['route_name' => 'Purchaser Vouchers Store', 'route' => 'purchaser.vouchers.store'],
            ['route_name' => 'Purchaser Vouchers Update', 'route' => 'purchaser.vouchers.update'],
            ['route_name' => 'Purchaser Vouchers Destroy', 'route' => 'purchaser.vouchers.destroy'],
            ['route_name' => 'Purchaser Vouchers Print', 'route' => 'purchaser.vouchers.print'],
            ['route_name' => 'Purchaser Vouchers Print All', 'route' => 'purchaser.vouchers.printAll'],
            ['route_name' => 'Purchaser Petty Cashes', 'route' => 'purchaser.petty-cashes'],
            ['route_name' => 'Purchaser Petty Cashes Store', 'route' => 'purchaser.petty-cashes.store'],
            ['route_name' => 'Purchaser Petty Cashes Details Store', 'route' => 'purchaser.petty-cashes.details.store'],
            ['route_name' => 'Purchaser Head Pricing Rules Index', 'route' => 'purchaser.head-pricing-rules.index'],
            ['route_name' => 'Purchaser Head Pricing Rules Store', 'route' => 'purchaser.head-pricing-rules.store'],
            ['route_name' => 'Purchaser Head Pricing Rules Update', 'route' => 'purchaser.head-pricing-rules.update'],
            ['route_name' => 'Purchaser Head Pricing Rules Destroy', 'route' => 'purchaser.head-pricing-rules.destroy'],
            ['route_name' => 'Purchaser Pricing Schemes Store', 'route' => 'purchaser.pricing-schemes.store'],
            ['route_name' => 'Purchaser Pricing Schemes Update', 'route' => 'purchaser.pricing-schemes.update'],
            ['route_name' => 'Purchaser Inventory Report Index', 'route' => 'purchaser.inventory.report.index'],
            ['route_name' => 'Purchaser Inventory Fetch Report', 'route' => 'purchaser.inventory.fetch-inventory-report'],
            ['route_name' => 'Purchaser Inventory Print Report PDF', 'route' => 'purchaser.inventory.print-inventory-report-pdf'],
            ['route_name' => 'Purchaser Expenses Report Index', 'route' => 'purchaser.expenses.report.index'],
            ['route_name' => 'Purchaser Expenses Fetch Report', 'route' => 'purchaser.expenses.fetch-expense-report'],
            ['route_name' => 'Purchaser Expenses Print Report PDF', 'route' => 'purchaser.expenses.print-expense-report-pdf'],
            ['route_name' => 'Purchaser Sales Report Index', 'route' => 'purchaser.sales.report.index'],
            ['route_name' => 'Purchaser Sales Fetch Report', 'route' => 'purchaser.sales.fetch-sales-report'],
            ['route_name' => 'Purchaser Sales Print Report PDF', 'route' => 'purchaser.sales.print-sales-report-pdf'],
            ['route_name' => 'Purchaser My Records', 'route' => 'purchaser.myrecords'],
            ['route_name' => 'Purchaser Clock In', 'route' => 'purchaser.clockin'],
            ['route_name' => 'Purchaser Clock Out', 'route' => 'purchaser.clockout'],
            ['route_name' => 'Purchaser Overtimes Store', 'route' => 'purchaser.overtimes.store'],
            ['route_name' => 'Purchaser Employees Overtimes', 'route' => 'purchaser.employees.overtimes'],
            ['route_name' => 'Purchaser Overtimes Filter', 'route' => 'purchaser.overtimes.filter'],
            ['route_name' => 'Purchaser Overtimes Update Status', 'route' => 'purchaser.overtimes.update-status'],

            // Kitchen
            ['route_name' => 'Kitchen POS', 'route' => 'kitchen.pos'],
            ['route_name' => 'Kitchen Table Sessions', 'route' => 'kitchen.table_sessions'],
            ['route_name' => 'Kitchen POS Items', 'route' => 'kitchen.pos-items'],
            ['route_name' => 'Kitchen Verify Voucher', 'route' => 'kitchen.pos.verify-voucher'],
            ['route_name' => 'Kitchen Verify Manager Password', 'route' => 'kitchen.verify-manager-password'],
            ['route_name' => 'Kitchen Orders', 'route' => 'kitchen.orders'],
            ['route_name' => 'Kitchen Orders Fetch Filtered', 'route' => 'kitchen.orders.fetch-filtered-orders'],
            ['route_name' => 'Kitchen Orders Store', 'route' => 'kitchen.orders.store'],
            ['route_name' => 'Kitchen Orders Cancel', 'route' => 'kitchen.orders.cancel'],
            ['route_name' => 'Kitchen Orders PDF', 'route' => 'kitchen.orders.pdf'],
            ['route_name' => 'Kitchen Orders Store Items', 'route' => 'kitchen.orders.store-items'],
            ['route_name' => 'Kitchen Orders Cancel Item', 'route' => 'kitchen.orders.cancel_item'],
            ['route_name' => 'Kitchen Orders Refresh Computation', 'route' => 'kitchen.orders.refresh-computation'],
            ['route_name' => 'Kitchen Orders Store Leftover', 'route' => 'kitchen.orders.store-leftover'],
            ['route_name' => 'Kitchen Orders Table Session Addons Store', 'route' => 'kitchen.orders.table_session_addons.store'],
            ['route_name' => 'Kitchen Orders Table Session Addons Void', 'route' => 'kitchen.orders.table_session_addons.void'],
            ['route_name' => 'Kitchen Menus', 'route' => 'kitchen.menus'],
            ['route_name' => 'Kitchen Menus Edit', 'route' => 'kitchen.menus.edit'],
            ['route_name' => 'Kitchen Menus Store', 'route' => 'kitchen.menus.store'],
            ['route_name' => 'Kitchen Reports', 'route' => 'kitchen.reports'],
            ['route_name' => 'Kitchen Expenses', 'route' => 'kitchen.expenses'],
            ['route_name' => 'Kitchen Expenses Fetch Filtered', 'route' => 'kitchen.expenses.fetch-filtered-expenses'],
            ['route_name' => 'Kitchen Expenses Store', 'route' => 'kitchen.expenses.store'],
            ['route_name' => 'Kitchen Table Occupancies', 'route' => 'kitchen.table_occupancies'],
            ['route_name' => 'Kitchen Table Admission', 'route' => 'kitchen.table_admission'],
            ['route_name' => 'Kitchen Table Occupancies Assign', 'route' => 'kitchen.table_occupancies.assign'],
            ['route_name' => 'Kitchen Table Occupancies Update', 'route' => 'kitchen.table_occupancies.update'],
            ['route_name' => 'Kitchen Table Occupancies Cancel', 'route' => 'kitchen.table_occupancies.cancel'],
            ['route_name' => 'Kitchen Table Admission Assign', 'route' => 'kitchen.table_admission.assign'],
            ['route_name' => 'Kitchen Reservations Index', 'route' => 'kitchen.reservations.index'],
            ['route_name' => 'Kitchen Reservations Create', 'route' => 'kitchen.reservations.create'],
            ['route_name' => 'Kitchen Reservations Store', 'route' => 'kitchen.reservations.store'],
            ['route_name' => 'Kitchen Reservations Show', 'route' => 'kitchen.reservations.show'],
            ['route_name' => 'Kitchen Reservations Edit', 'route' => 'kitchen.reservations.edit'],
            ['route_name' => 'Kitchen Reservations Update', 'route' => 'kitchen.reservations.update'],
            ['route_name' => 'Kitchen Reservations Destroy', 'route' => 'kitchen.reservations.destroy'],
            ['route_name' => 'Kitchen Inventory', 'route' => 'kitchen.inventory'],
            ['route_name' => 'Kitchen Inventory Items', 'route' => 'kitchen.inventory.items'],
            ['route_name' => 'Kitchen Inventory Items Store', 'route' => 'kitchen.inventory.items.store'],
            ['route_name' => 'Kitchen Inventory Stock In', 'route' => 'kitchen.inventory.stock-in'],
            ['route_name' => 'Kitchen Inventory Stock Out', 'route' => 'kitchen.inventory.stock-out'],
            ['route_name' => 'Kitchen Inventory Categories', 'route' => 'kitchen.inventory.categories'],
            ['route_name' => 'Kitchen Inventory Categories Store', 'route' => 'kitchen.inventory.categories.store'],
            ['route_name' => 'Kitchen Inventory General Report', 'route' => 'kitchen.inventory.general-report'],
            ['route_name' => 'Kitchen Employees Index', 'route' => 'kitchen.employees.index'],
            ['route_name' => 'Kitchen Employees Store', 'route' => 'kitchen.employees.store'],
            ['route_name' => 'Kitchen Employees Edit', 'route' => 'kitchen.employees.edit'],
            ['route_name' => 'Kitchen Employment Edit', 'route' => 'kitchen.employment.edit'],
            ['route_name' => 'Kitchen Employees Schedules Store', 'route' => 'kitchen.employees.schedules.store'],
            ['route_name' => 'Kitchen Employees Schedules Batch Store', 'route' => 'kitchen.employees.schedules.batchStore'],
            ['route_name' => 'Kitchen Employees Schedules Update', 'route' => 'kitchen.employees.schedules.update'],
            ['route_name' => 'Kitchen Employees Schedule', 'route' => 'kitchen.employees.schedule'],
            ['route_name' => 'Kitchen Employees Schedules Print', 'route' => 'kitchen.employees.schedules.print'],
            ['route_name' => 'Kitchen Employees Schedules Print All', 'route' => 'kitchen.employees.schedules.printAll'],
            ['route_name' => 'Kitchen Employment Update', 'route' => 'kitchen.employment.update'],
            ['route_name' => 'Kitchen Employment Documents Upload', 'route' => 'kitchen.employment.documents.upload'],
            ['route_name' => 'Kitchen Employees DTR', 'route' => 'kitchen.employees.dtr'],
            ['route_name' => 'Kitchen Employees DTR Update', 'route' => 'kitchen.employees.dtr.update'],
            ['route_name' => 'Kitchen Employees Payroll Attendance PDF', 'route' => 'kitchen.employees.payroll.attendance.pdf'],
            ['route_name' => 'Kitchen Generate Payroll', 'route' => 'kitchen.generate-payroll'],
            ['route_name' => 'Kitchen Payroll Summary', 'route' => 'kitchen.payroll.summary'],
            ['route_name' => 'Kitchen Payroll Post', 'route' => 'kitchen.payroll.post'],
            ['route_name' => 'Kitchen Payroll Index', 'route' => 'kitchen.payroll.index'],
            ['route_name' => 'Kitchen Payroll View Details', 'route' => 'kitchen.payroll.view-payroll-details'],
            ['route_name' => 'Kitchen Payroll Deduction Post', 'route' => 'kitchen.payroll.deduction.post'],
            ['route_name' => 'Kitchen Payroll Payslip Print Single', 'route' => 'kitchen.payroll.payslip.print.single'],
            ['route_name' => 'Kitchen Payroll Payslip Print Selected', 'route' => 'kitchen.payroll.payslip.print.selected'],
            ['route_name' => 'Kitchen Payroll Summary Print', 'route' => 'kitchen.payroll.summary.print'],
            ['route_name' => 'Kitchen Vouchers Index', 'route' => 'kitchen.vouchers.index'],
            ['route_name' => 'Kitchen Vouchers Store', 'route' => 'kitchen.vouchers.store'],
            ['route_name' => 'Kitchen Vouchers Update', 'route' => 'kitchen.vouchers.update'],
            ['route_name' => 'Kitchen Vouchers Destroy', 'route' => 'kitchen.vouchers.destroy'],
            ['route_name' => 'Kitchen Vouchers Print', 'route' => 'kitchen.vouchers.print'],
            ['route_name' => 'Kitchen Vouchers Print All', 'route' => 'kitchen.vouchers.printAll'],
            ['route_name' => 'Kitchen Petty Cashes', 'route' => 'kitchen.petty-cashes'],
            ['route_name' => 'Kitchen Petty Cashes Store', 'route' => 'kitchen.petty-cashes.store'],
            ['route_name' => 'Kitchen Petty Cashes Details Store', 'route' => 'kitchen.petty-cashes.details.store'],
            ['route_name' => 'Kitchen Head Pricing Rules Index', 'route' => 'kitchen.head-pricing-rules.index'],
            ['route_name' => 'Kitchen Head Pricing Rules Store', 'route' => 'kitchen.head-pricing-rules.store'],
            ['route_name' => 'Kitchen Head Pricing Rules Update', 'route' => 'kitchen.head-pricing-rules.update'],
            ['route_name' => 'Kitchen Head Pricing Rules Destroy', 'route' => 'kitchen.head-pricing-rules.destroy'],
            ['route_name' => 'Kitchen Pricing Schemes Store', 'route' => 'kitchen.pricing-schemes.store'],
            ['route_name' => 'Kitchen Pricing Schemes Update', 'route' => 'kitchen.pricing-schemes.update'],
            ['route_name' => 'Kitchen Inventory Report Index', 'route' => 'kitchen.inventory.report.index'],
            ['route_name' => 'Kitchen Inventory Fetch Report', 'route' => 'kitchen.inventory.fetch-inventory-report'],
            ['route_name' => 'Kitchen Inventory Print Report PDF', 'route' => 'kitchen.inventory.print-inventory-report-pdf'],
            ['route_name' => 'Kitchen Expenses Report Index', 'route' => 'kitchen.expenses.report.index'],
            ['route_name' => 'Kitchen Expenses Fetch Report', 'route' => 'kitchen.expenses.fetch-expense-report'],
            ['route_name' => 'Kitchen Expenses Print Report PDF', 'route' => 'kitchen.expenses.print-expense-report-pdf'],
            ['route_name' => 'Kitchen Sales Report Index', 'route' => 'kitchen.sales.report.index'],
            ['route_name' => 'Kitchen Sales Fetch Report', 'route' => 'kitchen.sales.fetch-sales-report'],
            ['route_name' => 'Kitchen Sales Print Report PDF', 'route' => 'kitchen.sales.print-sales-report-pdf'],
            ['route_name' => 'Kitchen My Records', 'route' => 'kitchen.myrecords'],
            ['route_name' => 'Kitchen Clock In', 'route' => 'kitchen.clockin'],
            ['route_name' => 'Kitchen Clock Out', 'route' => 'kitchen.clockout'],
            ['route_name' => 'Kitchen Overtimes Store', 'route' => 'kitchen.overtimes.store'],
            ['route_name' => 'Kitchen Employees Overtimes', 'route' => 'kitchen.employees.overtimes'],
            ['route_name' => 'Kitchen Overtimes Filter', 'route' => 'kitchen.overtimes.filter'],
            ['route_name' => 'Kitchen Overtimes Update Status', 'route' => 'kitchen.overtimes.update-status'],

            // HR
            ['route_name' => 'HR POS', 'route' => 'hr.pos'],
            ['route_name' => 'HR Table Sessions', 'route' => 'hr.table_sessions'],
            ['route_name' => 'HR POS Items', 'route' => 'hr.pos-items'],
            ['route_name' => 'HR Verify Voucher', 'route' => 'hr.pos.verify-voucher'],
            ['route_name' => 'HR Verify Manager Password', 'route' => 'hr.verify-manager-password'],
            ['route_name' => 'HR Orders', 'route' => 'hr.orders'],
            ['route_name' => 'HR Orders Fetch Filtered', 'route' => 'hr.orders.fetch-filtered-orders'],
            ['route_name' => 'HR Orders Store', 'route' => 'hr.orders.store'],
            ['route_name' => 'HR Orders Cancel', 'route' => 'hr.orders.cancel'],
            ['route_name' => 'HR Orders PDF', 'route' => 'hr.orders.pdf'],
            ['route_name' => 'HR Orders Store Items', 'route' => 'hr.orders.store-items'],
            ['route_name' => 'HR Orders Cancel Item', 'route' => 'hr.orders.cancel_item'],
            ['route_name' => 'HR Orders Refresh Computation', 'route' => 'hr.orders.refresh-computation'],
            ['route_name' => 'HR Orders Store Leftover', 'route' => 'hr.orders.store-leftover'],
            ['route_name' => 'HR Orders Table Session Addons Store', 'route' => 'hr.orders.table_session_addons.store'],
            ['route_name' => 'HR Orders Table Session Addons Void', 'route' => 'hr.orders.table_session_addons.void'],
            ['route_name' => 'HR Menus', 'route' => 'hr.menus'],
            ['route_name' => 'HR Menus Edit', 'route' => 'hr.menus.edit'],
            ['route_name' => 'HR Menus Store', 'route' => 'hr.menus.store'],
            ['route_name' => 'HR Reports', 'route' => 'hr.reports'],
            ['route_name' => 'HR Expenses', 'route' => 'hr.expenses'],
            ['route_name' => 'HR Expenses Fetch Filtered', 'route' => 'hr.expenses.fetch-filtered-expenses'],
            ['route_name' => 'HR Expenses Store', 'route' => 'hr.expenses.store'],
            ['route_name' => 'HR Table Occupancies', 'route' => 'hr.table_occupancies'],
            ['route_name' => 'HR Table Admission', 'route' => 'hr.table_admission'],
            ['route_name' => 'HR Table Occupancies Assign', 'route' => 'hr.table_occupancies.assign'],
            ['route_name' => 'HR Table Occupancies Update', 'route' => 'hr.table_occupancies.update'],
            ['route_name' => 'HR Table Occupancies Cancel', 'route' => 'hr.table_occupancies.cancel'],
            ['route_name' => 'HR Table Admission Assign', 'route' => 'hr.table_admission.assign'],
            ['route_name' => 'HR Reservations Index', 'route' => 'hr.reservations.index'],
            ['route_name' => 'HR Reservations Create', 'route' => 'hr.reservations.create'],
            ['route_name' => 'HR Reservations Store', 'route' => 'hr.reservations.store'],
            ['route_name' => 'HR Reservations Show', 'route' => 'hr.reservations.show'],
            ['route_name' => 'HR Reservations Edit', 'route' => 'hr.reservations.edit'],
            ['route_name' => 'HR Reservations Update', 'route' => 'hr.reservations.update'],
            ['route_name' => 'HR Reservations Destroy', 'route' => 'hr.reservations.destroy'],
            ['route_name' => 'HR Inventory', 'route' => 'hr.inventory'],
            ['route_name' => 'HR Inventory Items', 'route' => 'hr.inventory.items'],
            ['route_name' => 'HR Inventory Items Store', 'route' => 'hr.inventory.items.store'],
            ['route_name' => 'HR Inventory Stock In', 'route' => 'hr.inventory.stock-in'],
            ['route_name' => 'HR Inventory Stock Out', 'route' => 'hr.inventory.stock-out'],
            ['route_name' => 'HR Inventory Categories', 'route' => 'hr.inventory.categories'],
            ['route_name' => 'HR Inventory Categories Store', 'route' => 'hr.inventory.categories.store'],
            ['route_name' => 'HR Inventory General Report', 'route' => 'hr.inventory.general-report'],
            ['route_name' => 'HR Employees Index', 'route' => 'hr.employees.index'],
            ['route_name' => 'HR Employees Store', 'route' => 'hr.employees.store'],
            ['route_name' => 'HR Employees Edit', 'route' => 'hr.employees.edit'],
            ['route_name' => 'HR Employment Edit', 'route' => 'hr.employment.edit'],
            ['route_name' => 'HR Employees Schedules Store', 'route' => 'hr.employees.schedules.store'],
            ['route_name' => 'HR Employees Schedules Batch Store', 'route' => 'hr.employees.schedules.batchStore'],
            ['route_name' => 'HR Employees Schedules Update', 'route' => 'hr.employees.schedules.update'],
            ['route_name' => 'HR Employees Schedule', 'route' => 'hr.employees.schedule'],
            ['route_name' => 'HR Employees Schedules Print', 'route' => 'hr.employees.schedules.print'],
            ['route_name' => 'HR Employees Schedules Print All', 'route' => 'hr.employees.schedules.printAll'],
            ['route_name' => 'HR Employment Update', 'route' => 'hr.employment.update'],
            ['route_name' => 'HR Employment Documents Upload', 'route' => 'hr.employment.documents.upload'],
            ['route_name' => 'HR Employees DTR', 'route' => 'hr.employees.dtr'],
            ['route_name' => 'HR Employees DTR Update', 'route' => 'hr.employees.dtr.update'],
            ['route_name' => 'HR Employees Payroll Attendance PDF', 'route' => 'hr.employees.payroll.attendance.pdf'],
            ['route_name' => 'HR Generate Payroll', 'route' => 'hr.generate-payroll'],
            ['route_name' => 'HR Payroll Summary', 'route' => 'hr.payroll.summary'],
            ['route_name' => 'HR Payroll Post', 'route' => 'hr.payroll.post'],
            ['route_name' => 'HR Payroll Index', 'route' => 'hr.payroll.index'],
            ['route_name' => 'HR Payroll View Details', 'route' => 'hr.payroll.view-payroll-details'],
            ['route_name' => 'HR Payroll Deduction Post', 'route' => 'hr.payroll.deduction.post'],
            ['route_name' => 'HR Payroll Payslip Print Single', 'route' => 'hr.payroll.payslip.print.single'],
            ['route_name' => 'HR Payroll Payslip Print Selected', 'route' => 'hr.payroll.payslip.print.selected'],
            ['route_name' => 'HR Payroll Summary Print', 'route' => 'hr.payroll.summary.print'],
            ['route_name' => 'HR Vouchers Index', 'route' => 'hr.vouchers.index'],
            ['route_name' => 'HR Vouchers Store', 'route' => 'hr.vouchers.store'],
            ['route_name' => 'HR Vouchers Update', 'route' => 'hr.vouchers.update'],
            ['route_name' => 'HR Vouchers Destroy', 'route' => 'hr.vouchers.destroy'],
            ['route_name' => 'HR Vouchers Print', 'route' => 'hr.vouchers.print'],
            ['route_name' => 'HR Vouchers Print All', 'route' => 'hr.vouchers.printAll'],
            ['route_name' => 'HR Petty Cashes', 'route' => 'hr.petty-cashes'],
            ['route_name' => 'HR Petty Cashes Store', 'route' => 'hr.petty-cashes.store'],
            ['route_name' => 'HR Petty Cashes Details Store', 'route' => 'hr.petty-cashes.details.store'],
            ['route_name' => 'HR Head Pricing Rules Index', 'route' => 'hr.head-pricing-rules.index'],
            ['route_name' => 'HR Head Pricing Rules Store', 'route' => 'hr.head-pricing-rules.store'],
            ['route_name' => 'HR Head Pricing Rules Update', 'route' => 'hr.head-pricing-rules.update'],
            ['route_name' => 'HR Head Pricing Rules Destroy', 'route' => 'hr.head-pricing-rules.destroy'],
            ['route_name' => 'HR Pricing Schemes Store', 'route' => 'hr.pricing-schemes.store'],
            ['route_name' => 'HR Pricing Schemes Update', 'route' => 'hr.pricing-schemes.update'],
            ['route_name' => 'HR Inventory Report Index', 'route' => 'hr.inventory.report.index'],
            ['route_name' => 'HR Inventory Fetch Report', 'route' => 'hr.inventory.fetch-inventory-report'],
            ['route_name' => 'HR Inventory Print Report PDF', 'route' => 'hr.inventory.print-inventory-report-pdf'],
            ['route_name' => 'HR Expenses Report Index', 'route' => 'hr.expenses.report.index'],
            ['route_name' => 'HR Expenses Fetch Report', 'route' => 'hr.expenses.fetch-expense-report'],
            ['route_name' => 'HR Expenses Print Report PDF', 'route' => 'hr.expenses.print-expense-report-pdf'],
            ['route_name' => 'HR Sales Report Index', 'route' => 'hr.sales.report.index'],
            ['route_name' => 'HR Sales Fetch Report', 'route' => 'hr.sales.fetch-sales-report'],
            ['route_name' => 'HR Sales Print Report PDF', 'route' => 'hr.sales.print-sales-report-pdf'],
            ['route_name' => 'HR My Records', 'route' => 'hr.myrecords'],
            ['route_name' => 'HR Clock In', 'route' => 'hr.clockin'],
            ['route_name' => 'HR Clock Out', 'route' => 'hr.clockout'],
            ['route_name' => 'HR Overtimes Store', 'route' => 'hr.overtimes.store'],
            ['route_name' => 'HR Employees Overtimes', 'route' => 'hr.employees.overtimes'],
            ['route_name' => 'HR Overtimes Filter', 'route' => 'hr.overtimes.filter'],
            ['route_name' => 'HR Overtimes Update Status', 'route' => 'hr.overtimes.update-status'],

            // Finance
            ['route_name' => 'Finance POS', 'route' => 'finance.pos'],
            ['route_name' => 'Finance Table Sessions', 'route' => 'finance.table_sessions'],
            ['route_name' => 'Finance POS Items', 'route' => 'finance.pos-items'],
            ['route_name' => 'Finance Verify Voucher', 'route' => 'finance.pos.verify-voucher'],
            ['route_name' => 'Finance Verify Manager Password', 'route' => 'finance.verify-manager-password'],
            ['route_name' => 'Finance Orders', 'route' => 'finance.orders'],
            ['route_name' => 'Finance Orders Fetch Filtered', 'route' => 'finance.orders.fetch-filtered-orders'],
            ['route_name' => 'Finance Orders Store', 'route' => 'finance.orders.store'],
            ['route_name' => 'Finance Orders Cancel', 'route' => 'finance.orders.cancel'],
            ['route_name' => 'Finance Orders PDF', 'route' => 'finance.orders.pdf'],
            ['route_name' => 'Finance Orders Store Items', 'route' => 'finance.orders.store-items'],
            ['route_name' => 'Finance Orders Cancel Item', 'route' => 'finance.orders.cancel_item'],
            ['route_name' => 'Finance Orders Refresh Computation', 'route' => 'finance.orders.refresh-computation'],
            ['route_name' => 'Finance Orders Store Leftover', 'route' => 'finance.orders.store-leftover'],
            ['route_name' => 'Finance Orders Table Session Addons Store', 'route' => 'finance.orders.table_session_addons.store'],
            ['route_name' => 'Finance Orders Table Session Addons Void', 'route' => 'finance.orders.table_session_addons.void'],
            ['route_name' => 'Finance Menus', 'route' => 'finance.menus'],
            ['route_name' => 'Finance Menus Edit', 'route' => 'finance.menus.edit'],
            ['route_name' => 'Finance Menus Store', 'route' => 'finance.menus.store'],
            ['route_name' => 'Finance Reports', 'route' => 'finance.reports'],
            ['route_name' => 'Finance Expenses', 'route' => 'finance.expenses'],
            ['route_name' => 'Finance Expenses Fetch Filtered', 'route' => 'finance.expenses.fetch-filtered-expenses'],
            ['route_name' => 'Finance Expenses Store', 'route' => 'finance.expenses.store'],
            ['route_name' => 'Finance Table Occupancies', 'route' => 'finance.table_occupancies'],
            ['route_name' => 'Finance Table Admission', 'route' => 'finance.table_admission'],
            ['route_name' => 'Finance Table Occupancies Assign', 'route' => 'finance.table_occupancies.assign'],
            ['route_name' => 'Finance Table Occupancies Update', 'route' => 'finance.table_occupancies.update'],
            ['route_name' => 'Finance Table Occupancies Cancel', 'route' => 'finance.table_occupancies.cancel'],
            ['route_name' => 'Finance Table Admission Assign', 'route' => 'finance.table_admission.assign'],
            ['route_name' => 'Finance Reservations Index', 'route' => 'finance.reservations.index'],
            ['route_name' => 'Finance Reservations Create', 'route' => 'finance.reservations.create'],
            ['route_name' => 'Finance Reservations Store', 'route' => 'finance.reservations.store'],
            ['route_name' => 'Finance Reservations Show', 'route' => 'finance.reservations.show'],
            ['route_name' => 'Finance Reservations Edit', 'route' => 'finance.reservations.edit'],
            ['route_name' => 'Finance Reservations Update', 'route' => 'finance.reservations.update'],
            ['route_name' => 'Finance Reservations Destroy', 'route' => 'finance.reservations.destroy'],
            ['route_name' => 'Finance Inventory', 'route' => 'finance.inventory'],
            ['route_name' => 'Finance Inventory Items', 'route' => 'finance.inventory.items'],
            ['route_name' => 'Finance Inventory Items Store', 'route' => 'finance.inventory.items.store'],
            ['route_name' => 'Finance Inventory Stock In', 'route' => 'finance.inventory.stock-in'],
            ['route_name' => 'Finance Inventory Stock Out', 'route' => 'finance.inventory.stock-out'],
            ['route_name' => 'Finance Inventory Categories', 'route' => 'finance.inventory.categories'],
            ['route_name' => 'Finance Inventory Categories Store', 'route' => 'finance.inventory.categories.store'],
            ['route_name' => 'Finance Inventory General Report', 'route' => 'finance.inventory.general-report'],
            ['route_name' => 'Finance Employees Index', 'route' => 'finance.employees.index'],
            ['route_name' => 'Finance Employees Store', 'route' => 'finance.employees.store'],
            ['route_name' => 'Finance Employees Edit', 'route' => 'finance.employees.edit'],
            ['route_name' => 'Finance Employment Edit', 'route' => 'finance.employment.edit'],
            ['route_name' => 'Finance Employees Schedules Store', 'route' => 'finance.employees.schedules.store'],
            ['route_name' => 'Finance Employees Schedules Batch Store', 'route' => 'finance.employees.schedules.batchStore'],
            ['route_name' => 'Finance Employees Schedules Update', 'route' => 'finance.employees.schedules.update'],
            ['route_name' => 'Finance Employees Schedule', 'route' => 'finance.employees.schedule'],
            ['route_name' => 'Finance Employees Schedules Print', 'route' => 'finance.employees.schedules.print'],
            ['route_name' => 'Finance Employees Schedules Print All', 'route' => 'finance.employees.schedules.printAll'],
            ['route_name' => 'Finance Employment Update', 'route' => 'finance.employment.update'],
            ['route_name' => 'Finance Employment Documents Upload', 'route' => 'finance.employment.documents.upload'],
            ['route_name' => 'Finance Employees DTR', 'route' => 'finance.employees.dtr'],
            ['route_name' => 'Finance Employees DTR Update', 'route' => 'finance.employees.dtr.update'],
            ['route_name' => 'Finance Employees Payroll Attendance PDF', 'route' => 'finance.employees.payroll.attendance.pdf'],
            ['route_name' => 'Finance Generate Payroll', 'route' => 'finance.generate-payroll'],
            ['route_name' => 'Finance Payroll Summary', 'route' => 'finance.payroll.summary'],
            ['route_name' => 'Finance Payroll Post', 'route' => 'finance.payroll.post'],
            ['route_name' => 'Finance Payroll Index', 'route' => 'finance.payroll.index'],
            ['route_name' => 'Finance Payroll View Details', 'route' => 'finance.payroll.view-payroll-details'],
            ['route_name' => 'Finance Payroll Deduction Post', 'route' => 'finance.payroll.deduction.post'],
            ['route_name' => 'Finance Payroll Payslip Print Single', 'route' => 'finance.payroll.payslip.print.single'],
            ['route_name' => 'Finance Payroll Payslip Print Selected', 'route' => 'finance.payroll.payslip.print.selected'],
            ['route_name' => 'Finance Payroll Summary Print', 'route' => 'finance.payroll.summary.print'],
            ['route_name' => 'Finance Vouchers Index', 'route' => 'finance.vouchers.index'],
            ['route_name' => 'Finance Vouchers Store', 'route' => 'finance.vouchers.store'],
            ['route_name' => 'Finance Vouchers Update', 'route' => 'finance.vouchers.update'],
            ['route_name' => 'Finance Vouchers Destroy', 'route' => 'finance.vouchers.destroy'],
            ['route_name' => 'Finance Vouchers Print', 'route' => 'finance.vouchers.print'],
            ['route_name' => 'Finance Vouchers Print All', 'route' => 'finance.vouchers.printAll'],
            ['route_name' => 'Finance Petty Cashes', 'route' => 'finance.petty-cashes'],
            ['route_name' => 'Finance Petty Cashes Store', 'route' => 'finance.petty-cashes.store'],
            ['route_name' => 'Finance Petty Cashes Details Store', 'route' => 'finance.petty-cashes.details.store'],
            ['route_name' => 'Finance Head Pricing Rules Index', 'route' => 'finance.head-pricing-rules.index'],
            ['route_name' => 'Finance Head Pricing Rules Store', 'route' => 'finance.head-pricing-rules.store'],
            ['route_name' => 'Finance Head Pricing Rules Update', 'route' => 'finance.head-pricing-rules.update'],
            ['route_name' => 'Finance Head Pricing Rules Destroy', 'route' => 'finance.head-pricing-rules.destroy'],
            ['route_name' => 'Finance Pricing Schemes Store', 'route' => 'finance.pricing-schemes.store'],
            ['route_name' => 'Finance Pricing Schemes Update', 'route' => 'finance.pricing-schemes.update'],
            ['route_name' => 'Finance Inventory Report Index', 'route' => 'finance.inventory.report.index'],
            ['route_name' => 'Finance Inventory Fetch Report', 'route' => 'finance.inventory.fetch-inventory-report'],
            ['route_name' => 'Finance Inventory Print Report PDF', 'route' => 'finance.inventory.print-inventory-report-pdf'],
            ['route_name' => 'Finance Expenses Report Index', 'route' => 'finance.expenses.report.index'],
            ['route_name' => 'Finance Expenses Fetch Report', 'route' => 'finance.expenses.fetch-expense-report'],
            ['route_name' => 'Finance Expenses Print Report PDF', 'route' => 'finance.expenses.print-expense-report-pdf'],
            ['route_name' => 'Finance Sales Report Index', 'route' => 'finance.sales.report.index'],
            ['route_name' => 'Finance Sales Fetch Report', 'route' => 'finance.sales.fetch-sales-report'],
            ['route_name' => 'Finance Sales Print Report PDF', 'route' => 'finance.sales.print-sales-report-pdf'],
            ['route_name' => 'Finance My Records', 'route' => 'finance.myrecords'],
            ['route_name' => 'Finance Clock In', 'route' => 'finance.clockin'],
            ['route_name' => 'Finance Clock Out', 'route' => 'finance.clockout'],
            ['route_name' => 'Finance Overtimes Store', 'route' => 'finance.overtimes.store'],
            ['route_name' => 'Finance Employees Overtimes', 'route' => 'finance.employees.overtimes'],
            ['route_name' => 'Finance Overtimes Filter', 'route' => 'finance.overtimes.filter'],
            ['route_name' => 'Finance Overtimes Update Status', 'route' => 'finance.overtimes.update-status'],

            // Admin
            ['route_name' => 'Admin POS', 'route' => 'admin.pos'],
            ['route_name' => 'Admin Table Sessions', 'route' => 'admin.table_sessions'],
            ['route_name' => 'Admin POS Items', 'route' => 'admin.pos-items'],
            ['route_name' => 'Admin Verify Voucher', 'route' => 'admin.pos.verify-voucher'],
            ['route_name' => 'Admin Verify Manager Password', 'route' => 'admin.verify-manager-password'],
            ['route_name' => 'Admin Orders', 'route' => 'admin.orders'],
            ['route_name' => 'Admin Orders Fetch Filtered', 'route' => 'admin.orders.fetch-filtered-orders'],
            ['route_name' => 'Admin Orders Store', 'route' => 'admin.orders.store'],
            ['route_name' => 'Admin Orders Cancel', 'route' => 'admin.orders.cancel'],
            ['route_name' => 'Admin Orders PDF', 'route' => 'admin.orders.pdf'],
            ['route_name' => 'Admin Orders Store Items', 'route' => 'admin.orders.store-items'],
            ['route_name' => 'Admin Orders Cancel Item', 'route' => 'admin.orders.cancel_item'],
            ['route_name' => 'Admin Orders Refresh Computation', 'route' => 'admin.orders.refresh-computation'],
            ['route_name' => 'Admin Orders Store Leftover', 'route' => 'admin.orders.store-leftover'],
            ['route_name' => 'Admin Orders Table Session Addons Store', 'route' => 'admin.orders.table_session_addons.store'],
            ['route_name' => 'Admin Orders Table Session Addons Void', 'route' => 'admin.orders.table_session_addons.void'],
            ['route_name' => 'Admin Menus', 'route' => 'admin.menus'],
            ['route_name' => 'Admin Menus Edit', 'route' => 'admin.menus.edit'],
            ['route_name' => 'Admin Menus Store', 'route' => 'admin.menus.store'],
            ['route_name' => 'Admin Reports', 'route' => 'admin.reports'],
            ['route_name' => 'Admin Users', 'route' => 'admin.users'],
            ['route_name' => 'Admin Users Store', 'route' => 'admin.users.store'],
            ['route_name' => 'Admin Users Update', 'route' => 'admin.users.update'],
            ['route_name' => 'Admin Users Destroy', 'route' => 'admin.users.destroy'],
            ['route_name' => 'Admin Inventory', 'route' => 'admin.inventory'],
            ['route_name' => 'Admin Inventory Items', 'route' => 'admin.inventory.items'],
            ['route_name' => 'Admin Inventory Items Store', 'route' => 'admin.inventory.items.store'],
            ['route_name' => 'Admin Inventory Stock In', 'route' => 'admin.inventory.stock-in'],
            ['route_name' => 'Admin Inventory Stock Out', 'route' => 'admin.inventory.stock-out'],
            ['route_name' => 'Admin Inventory Categories', 'route' => 'admin.inventory.categories'],
            ['route_name' => 'Admin Inventory Categories Store', 'route' => 'admin.inventory.categories.store'],
            ['route_name' => 'Admin Inventory General Report', 'route' => 'admin.inventory.general-report'],
            ['route_name' => 'Admin Petty Cashes', 'route' => 'admin.petty-cashes'],
            ['route_name' => 'Admin Petty Cashes Store', 'route' => 'admin.petty-cashes.store'],
            ['route_name' => 'Admin Petty Cashes Details Store', 'route' => 'admin.petty-cashes.details.store'],
            ['route_name' => 'Admin Expenses', 'route' => 'admin.expenses'],
            ['route_name' => 'Admin Expenses Fetch Filtered', 'route' => 'admin.expenses.fetch-filtered-expenses'],
            ['route_name' => 'Admin Expenses Store', 'route' => 'admin.expenses.store'],
            ['route_name' => 'Admin Tables', 'route' => 'admin.tables'],
            ['route_name' => 'Admin Tables Store', 'route' => 'admin.tables.store'],
            ['route_name' => 'Admin Tables Update', 'route' => 'admin.tables.update'],
            ['route_name' => 'Admin Tables Destroy', 'route' => 'admin.tables.destroy'],
            ['route_name' => 'Admin Branches', 'route' => 'admin.branches'],
            ['route_name' => 'Admin Head Pricing Rules Index', 'route' => 'admin.head-pricing-rules.index'],
            ['route_name' => 'Admin Head Pricing Rules Store', 'route' => 'admin.head-pricing-rules.store'],
            ['route_name' => 'Admin Head Pricing Rules Update', 'route' => 'admin.head-pricing-rules.update'],
            ['route_name' => 'Admin Head Pricing Rules Destroy', 'route' => 'admin.head-pricing-rules.destroy'],
            ['route_name' => 'Admin Pricing Schemes Store', 'route' => 'admin.pricing-schemes.store'],
            ['route_name' => 'Admin Pricing Schemes Update', 'route' => 'admin.pricing-schemes.update'],
            ['route_name' => 'Admin Employees Index', 'route' => 'admin.employees.index'],
            ['route_name' => 'Admin Employees Store', 'route' => 'admin.employees.store'],
            ['route_name' => 'Admin Employees Edit', 'route' => 'admin.employees.edit'],
            ['route_name' => 'Admin Employment Edit', 'route' => 'admin.employment.edit'],
            ['route_name' => 'Admin Employees Schedules Store', 'route' => 'admin.employees.schedules.store'],
            ['route_name' => 'Admin Employees Schedules Batch Store', 'route' => 'admin.employees.schedules.batchStore'],
            ['route_name' => 'Admin Employees Schedules Update', 'route' => 'admin.employees.schedules.update'],
            ['route_name' => 'Admin Employees Schedule', 'route' => 'admin.employees.schedule'],
            ['route_name' => 'Admin Employees Schedules Print', 'route' => 'admin.employees.schedules.print'],
            ['route_name' => 'Admin Employees Schedules Print All', 'route' => 'admin.employees.schedules.printAll'],
            ['route_name' => 'Admin Employment Update', 'route' => 'admin.employment.update'],
            ['route_name' => 'Admin Employment Documents Upload', 'route' => 'admin.employment.documents.upload'],
            ['route_name' => 'Admin Employees DTR', 'route' => 'admin.employees.dtr'],
            ['route_name' => 'Admin Employees DTR Update', 'route' => 'admin.employees.dtr.update'],
            ['route_name' => 'Admin Employees Payroll Attendance PDF', 'route' => 'admin.employees.payroll.attendance.pdf'],
            ['route_name' => 'Admin Generate Payroll', 'route' => 'admin.generate-payroll'],
            ['route_name' => 'Admin Payroll Summary', 'route' => 'admin.payroll.summary'],
            ['route_name' => 'Admin Payroll Post', 'route' => 'admin.payroll.post'],
            ['route_name' => 'Admin Payroll Index', 'route' => 'admin.payroll.index'],
            ['route_name' => 'Admin Payroll View Details', 'route' => 'admin.payroll.view-payroll-details'],
            ['route_name' => 'Admin Payroll Deduction Post', 'route' => 'admin.payroll.deduction.post'],
            ['route_name' => 'Admin Payroll Payslip Print Single', 'route' => 'admin.payroll.payslip.print.single'],
            ['route_name' => 'Admin Payroll Payslip Print Selected', 'route' => 'admin.payroll.payslip.print.selected'],
            ['route_name' => 'Admin Payroll Summary Print', 'route' => 'admin.payroll.summary.print'],
            ['route_name' => 'Admin Vouchers Index', 'route' => 'admin.vouchers.index'],
            ['route_name' => 'Admin Vouchers Store', 'route' => 'admin.vouchers.store'],
            ['route_name' => 'Admin Vouchers Update', 'route' => 'admin.vouchers.update'],
            ['route_name' => 'Admin Vouchers Destroy', 'route' => 'admin.vouchers.destroy'],
            ['route_name' => 'Admin Vouchers Print', 'route' => 'admin.vouchers.print'],
            ['route_name' => 'Admin Vouchers Print All', 'route' => 'admin.vouchers.printAll'],
            ['route_name' => 'Admin Inventory Report Index', 'route' => 'admin.inventory.report.index'],
            ['route_name' => 'Admin Inventory Fetch Report', 'route' => 'admin.inventory.fetch-inventory-report'],
            ['route_name' => 'Admin Inventory Print Report PDF', 'route' => 'admin.inventory.print-inventory-report-pdf'],
            ['route_name' => 'Admin Expenses Report Index', 'route' => 'admin.expenses.report.index'],
            ['route_name' => 'Admin Expenses Fetch Report', 'route' => 'admin.expenses.fetch-expense-report'],
            ['route_name' => 'Admin Expenses Print Report PDF', 'route' => 'admin.expenses.print-expense-report-pdf'],
            ['route_name' => 'Admin Sales Report Index', 'route' => 'admin.sales.report.index'],
            ['route_name' => 'Admin Sales Fetch Report', 'route' => 'admin.sales.fetch-sales-report'],
            ['route_name' => 'Admin Sales Print Report PDF', 'route' => 'admin.sales.print-sales-report-pdf'],
            ['route_name' => 'Admin My Records', 'route' => 'admin.myrecords'],
            ['route_name' => 'Admin Clock In', 'route' => 'admin.clockin'],
            ['route_name' => 'Admin Clock Out', 'route' => 'admin.clockout'],
            ['route_name' => 'Admin Overtimes Store', 'route' => 'admin.overtimes.store'],
            ['route_name' => 'Admin Configurations', 'route' => 'admin.configurations'],
            ['route_name' => 'Admin Configurations Store', 'route' => 'admin.configurations.store'],
            ['route_name' => 'Admin Configurations Update', 'route' => 'admin.configurations.update'],
        ];

        $now = now();

        foreach ($routes as $item) {
            DB::table('app_routes')->updateOrInsert(
                ['route' => $item['route']],
                [
                    'route_name' => $item['route_name'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}