<!DOCTYPE html>
<html>
<head>
    <title>Daily Inventory Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12pt; }
        h2 { text-align: center; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th, td { border: 1px solid #000; padding: 6px; text-align: left; }
        th { background-color: #f2f2f2; }
        tfoot td { font-weight: bold; }
    </style>
</head>
<body>
    <h2>
        Daily Inventory Report - {{ ucfirst($reportType) }} - {{ $date }}
    </h2>

    <div class="report-meta">
        Generated By: {{ $user->name ?? 'N/A' }}<br>
        Generated On: {{ now()->format('Y-m-d H:i') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Ingredient</th>
                <th>Unit</th>
                @if($reportType === 'stock_out' || $reportType === 'all')
                    <th>Used Today</th>
                    <th>Unit Price (₱)</th>
                    <th>Total Cost (₱)</th>
                @endif
                @if($reportType === 'stock_in' || $reportType === 'all')
                    <th>Stock In Today</th>
                @endif
            </tr>
        </thead>
        <tbody>
            @php $grandTotal = 0; @endphp
            @foreach($reportData as $i => $item)
                @php
                    if($reportType === 'stock_out' || $reportType === 'all'){
                        $grandTotal += $item['total_cost'];
                    }
                @endphp
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $item['name'] }}</td>
                    <td>{{ $item['unit'] }}</td>

                    @if($reportType === 'stock_out' || $reportType === 'all')
                        <td>{{ $item['usedToday'] }}</td>
                        <td>{{ number_format($item['unit_price'], 2) }}</td>
                        <td>{{ number_format($item['total_cost'], 2) }}</td>
                    @endif

                    @if($reportType === 'stock_in' || $reportType === 'all')
                        <td>{{ $item['stockInToday'] ?? 0 }}</td>
                    @endif
                </tr>
            @endforeach
        </tbody>

        @if($reportType === 'stock_out' || $reportType === 'all')
            <tfoot>
                <tr>
                    <td colspan="{{ $reportType === 'all' ? 6 : 5 }}">Grand Total</td>
                    <td>{{ number_format($grandTotal, 2) }}</td>
                </tr>
            </tfoot>
        @endif
    </table>

    <p>Generated on: {{ now()->format('Y-m-d H:i') }}</p>
</body>
</html>
