<!DOCTYPE html>
<html>
<head>
    <title>Inventory Report</title>

    <style>
        body { font-family: Arial, sans-serif; font-size: 11pt; }
        h2 { text-align: center; margin-bottom: 5px; }
        .meta { font-size: 9pt; margin-bottom: 15px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #000; padding: 6px; }
        th { background-color: #f2f2f2; text-align: center; }
        td { text-align: left; }
        tfoot td { font-weight: bold; }
        .right { text-align: right; }
        .center { text-align: center; }
    </style>
</head>

<body>

    <h2>
        @if($isDaily)
            Daily Inventory Report - {{ ucfirst($reportType) }}
            ({{ \Carbon\Carbon::parse($start)->format('M d, Y') }})
        @else
            Inventory Report - {{ ucfirst($reportType) }}
            ({{ \Carbon\Carbon::parse($start)->format('M d, Y') }}
            -
            {{ \Carbon\Carbon::parse($end)->format('M d, Y') }})
        @endif
    </h2>

    <div class="meta">
        Generated By: {{ $user->name ?? 'N/A' }} <br>
        Generated On: {{ now()->format('M d, Y h:i A') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Category</th>
                <th>Item Name</th>
                <th>Unit</th>

                @if($reportType === 'stockout' || $reportType === 'all')
                    <th>Stock Out</th>
                    <th>Unit Price (₱)</th>
                    <th>Total Cost (₱)</th>
                @endif

                @if($reportType === 'stockin' || $reportType === 'all')
                    <th>Stock In</th>
                @endif
            </tr>
        </thead>

        <tbody>
            @php
                $grandStockOut = 0;
                $grandStockIn = 0;
                $grandCost = 0;
            @endphp

            @foreach($reportData as $index => $item)

                @php
                    $grandStockOut += $item['stockOutQty'] ?? 0;
                    $grandStockIn  += $item['stockInQty'] ?? 0;
                    $grandCost     += $item['total_cost'] ?? 0;
                @endphp

                <tr>
                    <td class="center">{{ $index + 1 }}</td>
                    <td>{{ $item['category'] }}</td>
                    <td>{{ $item['name'] }}</td>
                    <td class="center">{{ $item['unit'] }}</td>

                    @if($reportType === 'stockout' || $reportType === 'all')
                        <td class="center">{{ $item['stockOutQty'] }}</td>
                        <td class="right">{{ number_format($item['unit_price'], 2) }}</td>
                        <td class="right">{{ number_format($item['total_cost'], 2) }}</td>
                    @endif

                    @if($reportType === 'stockin' || $reportType === 'all')
                        <td class="center">{{ $item['stockInQty'] }}</td>
                    @endif
                </tr>

            @endforeach
        </tbody>

        <tfoot>
            <tr>
                <td colspan="4" class="right">GRAND TOTAL</td>

                @if($reportType === 'stockout' || $reportType === 'all')
                    <td class="center">{{ $grandStockOut }}</td>
                    <td></td>
                    <td class="right">{{ number_format($grandCost, 2) }}</td>
                @endif

                @if($reportType === 'stockin' || $reportType === 'all')
                    <td class="center">{{ $grandStockIn }}</td>
                @endif
            </tr>
        </tfoot>

    </table>

</body>
</html>