<!DOCTYPE html>
<html>
<head>
    <title>Payroll Summary</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px; }
        .title { font-size: 18px; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #000; padding: 5px; text-align: left; }
        th { background: #f0f0f0; }
        .footer { margin-top: 20px; font-size: 12px; }
        tfoot td { font-weight: bold; }
    </style>
</head>
<body>

    <div class="header">
        <div class="title">{{ $branch->name ?? 'N/A' }} | Payroll Summary</div>
        <div>
            Generated By: {{ $generated_by }}
        </div>
    </div>

    <p>Period: {{ $start->format('M d, Y') }} - {{ $end->format('M d, Y') }}</p>

    <table>
        <thead>
            <tr>
                <th>Employee Code</th>
                <th>Name</th>
                <th>Total Days</th>
                <th>Total Hours</th>
                <!-- <th>Overtime Hours</th> -->
                <th>Total Late (min)</th>
                <th>Total Undertime (min)</th>
                <th>Total Earnings</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($payrollData as $row)
            <tr>
                <td>{{ $row['employee_code'] }}</td>
                <td>{{ $row['first_name'] }} {{ $row['last_name'] }}</td>
                <td>{{ $row['total_days'] }}</td>
                <td>{{ $row['total_hours'] }}</td>
                <td>{{ $row['total_late'] }}</td>
                <td>{{ $row['total_undertime'] }}</td>
                <td>{{ number_format($row['total_earnings'], 2) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2" style="text-align: right;">Grand Total:</td>
                <td>{{ collect($payrollData)->sum('total_days') }}</td>
                <td>{{ collect($payrollData)->sum('total_hours') }}</td>
                <td>{{ collect($payrollData)->sum('total_late') }}</td>
                <td>{{ collect($payrollData)->sum('total_undertime') }}</td>
                <td>{{ number_format(collect($payrollData)->sum('total_earnings'), 2) }}</td>
            </tr>
        </tfoot>
    </table>

</body>
</html>