<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Expenses Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        table { border-collapse: collapse; width: 100%; margin-top: 15px; }
        th, td { border: 1px solid #000; padding: 6px; text-align: left; }
        th { background-color: #f0f0f0; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .header { margin-bottom: 10px; }
        .header div { margin-bottom: 3px; }
        .total-row { font-weight: bold; background-color: #f9f9f9; }
    </style>
</head>
<body>

    <div class="header">
        <div><strong>Expenses Report</strong></div>
        <div>
            <strong>Report Type:</strong> {{ ucfirst($reportType) }}
        </div>
        <div>
            <strong>Date Range:</strong> {{ $start }} @if(!$isDaily) to {{ $end }} @endif
        </div>
        <div>
            <strong>Generated By:</strong> {{ $user->name }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th class="text-center">ID</th>
                <th>Category</th>
                <th>Description</th>
                <th class="text-center">Expense Date</th>
                <th class="text-right">Amount (₱)</th>
                <th>Created By</th>
            </tr>
        </thead>
        <tbody>
            @php
                $grandTotal = 0;
            @endphp

            @foreach($reportData as $expense)
                @php
                    $grandTotal += $expense->amount;
                @endphp
                <tr>
                    <td class="text-center">{{ $expense->id }}</td>
                    <td>{{ $expense->category->name ?? '-' }}</td>
                    <td>{{ $expense->description }}</td>
                    <td class="text-center">{{ $expense->expense_date }}</td>
                    <td class="text-right">₱{{ number_format($expense->amount, 2) }}</td>
                    <td>{{ $expense->creator->name ?? '-' }}</td>
                </tr>
            @endforeach

            @if($reportData->isEmpty())
                <tr>
                    <td colspan="6" class="text-center">No records found</td>
                </tr>
            @endif
        </tbody>

        @if($reportData->isNotEmpty())
        <tfoot>
            <tr class="total-row">
                <td colspan="4" class="text-right">Grand Total (₱):</td>
                <td class="text-right">{{ number_format($grandTotal, 2) }}</td>
                <td></td>
            </tr>
        </tfoot>
        @endif
    </table>

</body>
</html>