{{-- resources/views/reports/InventoryReport.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inventory Report</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        table { border-collapse: collapse; width: 100%; margin-top: 15px; }
        th, td { border: 1px solid #000; padding: 6px; text-align: left; }
        th { background-color: #f0f0f0; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .header { margin-bottom: 10px; }
        .header div { margin-bottom: 3px; }
        .total-row { font-weight: bold; background-color: #f9f9f9; }
    </style>
</head>
<body>

    <div class="header">
        <div><strong>Inventory Report</strong></div>
        <div>
            <strong>Report Type:</strong> {{ ucfirst($reportType) }}
        </div>
        <div>
            <strong>Date Range:</strong> {{ $start }} @if(!$isDaily) to {{ $end }} @endif
        </div>
        <div>
            <strong>Generated By:</strong> {{ $user->name }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th class="text-center">ID</th>
                <th>Category</th>
                <th>Item</th>
                <th>Unit</th>
                <th class="text-center">Current Stock</th>
                <th class="text-center">Stock In</th>
                <th class="text-center">Stock Out</th>
                <th class="text-right">Total Cost (₱)</th>
                <th>User</th>
            </tr>
        </thead>
        <tbody>
            @php
                $grandTotal = 0;
            @endphp
            @foreach($reportData as $movement)
                @php
                    // Always calculate cost based on stock out or stock in qty * unit price
                    $cost = ($movement['stockOutQty'] + $movement['stockInQty']) * $movement['unit_price'];
                    $grandTotal += $cost;
                @endphp
                <tr>
                    <td class="text-center">{{ $movement['id'] }}</td>
                    <td>{{ $movement['category'] }}</td>
                    <td>{{ $movement['name'] }}</td>
                    <td>{{ $movement['unit'] }}</td>
                    <td class="text-center"
                        @if($movement['current_quantity'] <= 5) style="color:red;" @else style="color:green;" @endif
                    >
                        {{ $movement['current_quantity'] }}
                    </td>
                    <td class="text-center">{{ $movement['stockInQty'] }}</td>
                    <td class="text-center">{{ $movement['stockOutQty'] }}</td>
                    <td class="text-right">₱{{ number_format($cost, 2) }}</td>
                    <td>{{ $movement['creator_name'] ?? '-' }}</td>
                </tr>
            @endforeach
            @if($reportData->isEmpty())
                <tr>
                    <td colspan="9" class="text-center">No records found</td>
                </tr>
            @endif
        </tbody>
        @if($reportData->isNotEmpty())
        <tfoot>
            <tr class="total-row">
                <td colspan="7" class="text-right">Grand Total (₱):</td>
                <td class="text-right">{{ number_format($grandTotal, 2) }}</td>
                <td></td>
            </tr>
        </tfoot>
        @endif
    </table>

</body>
</html>